# Custom Chatbot Project

TODO: In this cell, write an explanation of which dataset you have chosen and why it is appropriate for this task

I have chosen character description dataset for the following reasons:
1) It lets users ask question about characters in play, movie, reality show, musical etc
2) It can let user query about relationship between characters in a specific play, movie etc

## Data Wrangling

TODO: In the cells below, load your chosen dataset into a `pandas` dataframe with a column named `"text"`. This column should contain all of your text data, separated into at least 20 rows.

In [1]:
import openai
import pandas as pd
import numpy as np

In [2]:
openai.api_key = "YOUR API KEY"

In [3]:
!ls ./data/*

./data/2023_fashion_trends.csv	   ./data/nyc_food_scrap_drop_off_sites.csv
./data/character_descriptions.csv

In [4]:
!head ./data/character_descriptions.csv

In [5]:
df_char = pd.read_csv('./data/character_descriptions.csv')

In [6]:
df_char.Medium.value_counts()

Play              18
Reality Show       8
Musical            7
Movie              6
Sitcom             6
Limited Series     5
Opera              5
Name: Medium, dtype: int64

In [7]:
len(df_char), df_char.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         55 non-null     object
 1   Description  55 non-null     object
 2   Medium       55 non-null     object
 3   Setting      55 non-null     object
dtypes: object(4)
memory usage: 1.8+ KB

(55, None)

In [8]:
df_char.iloc[2]

Name                                                       Alice
Description    A woman in her late 30s, Alice is a warm and n...
Medium                                                      Play
Setting                                                  England
Name: 2, dtype: object

In [9]:
df_char.Name.value_counts()

Emily                   1
Sir Toby Belch          1
Sophia                  1
Noah                    1
Chloe                   1
Jake                    1
Prince Lorenzo          1
Signora Rosa            1
Baron Gustavo           1
Francesca               1
Don Carlo               1
Duke Orsino             1
Lady Olivia             1
Malvolio                1
Maya                    1
Viola                   1
Sir Andrew Aguecheek    1
Bianca                  1
Sebastian               1
Feste                   1
Antonio                 1
Abigail                 1
Thomas                  1
Reverend Brown          1
Captain James           1
Mrs. Mercer             1
James                   1
Marcus                  1
Jack                    1
Will                    1
Alice                   1
Tom                     1
Sarah                   1
George                  1
Rachel                  1
John                    1
Maria                   1
Caleb                   1
Tyler                   1
Sonya                   1
Manuel                  1
Mia                     1
Olivia                  1
Lucas                   1
Tahlia                  1
Max                     1
Ava                     1
Donna                   1
Johnny                  1
Sable                   1
Dolly                   1
Vixen                   1
Karma                   1
Crystal                 1
Mr. Mercer              1
Name: Name, dtype: int64

In [10]:
df_char

,Name,Description,Medium,Setting
0,Emily,"A young woman in her early 20s, Emily is an as...",Play,England
1,Jack,"A middle-aged man in his 40s, Jack is a succes...",Play,England
2,Alice,"A woman in her late 30s, Alice is a warm and n...",Play,England
3,Tom,"A man in his 50s, Tom is a retired soldier and...",Play,England
4,Sarah,"A woman in her mid-20s, Sarah is a free-spirit...",Play,England
5,George,"A man in his early 30s, George is a charming a...",Play,England
6,Rachel,"A woman in her late 20s, Rachel is a shy and i...",Play,England
7,John,"A man in his 60s, John is a retired professor ...",Play,England
8,Maria,"A middle-aged Latina woman in her 40s, Maria i...",Movie,Texas
9,Caleb,"A young African American man in his early 20s,...",Movie,Texas
10,Tyler,"A white man in his mid-30s, Tyler is a tough-a...",Movie,Texas
11,Sonya,"A white woman in her late 20s, Sonya is a free...",Movie,Texas
12,Manuel,"A middle-aged Hispanic man in his 50s, Manuel ...",Movie,Texas
13,Will,"A white man in his early 40s, Will is a succes...",Movie,Texas
14,Mia,"A young Australian woman in her mid-20s, Mia i...",Limited Series,Australia
15,Lucas,"A middle-aged Australian man in his 40s, Lucas...",Limited Series,Australia
16,Tahlia,A young Indigenous Australian woman in her ear...,Limited Series,Australia
17,Max,"A white Australian man in his late 20s, Max is...",Limited Series,Australia
18,Ava,"A middle-aged Australian woman in her 50s, Ava...",Limited Series,Australia
19,Donna,A seasoned performer with a larger-than-life p...,Musical,USA
20,Johnny,"A young up-and-coming performer, Johnny is ful...",Musical,USA
21,Sable,"A sultry and dramatic performer, Sable exudes ...",Musical,USA
22,Dolly,"A bubbly and vivacious performer, Dolly is a f...",Musical,USA
23,Vixen,"A fierce and competitive performer, Vixen is a...",Musical,USA
24,Karma,"A chameleon-like performer, Karma is known for...",Musical,USA
25,Crystal,"A quirky and imaginative performer, Crystal is...",Musical,USA
26,Olivia,A confident and charismatic marketing executiv...,Reality Show,USA
27,Marcus,"A charming and successful entrepreneur, Marcus...",Reality Show,USA
28,Maya,A kind and compassionate nurse with a heart of...,Reality Show,USA
29,James,"A handsome and athletic personal trainer, Jame...",Reality Show,USA
30,Sophia,"A fun-loving and adventurous travel blogger, S...",Reality Show,USA
31,Noah,"A quirky and creative graphic designer, Noah i...",Reality Show,USA
32,Chloe,"A driven and ambitious attorney, Chloe is alwa...",Reality Show,USA
33,Jake,"A laid-back and easygoing firefighter, Jake is...",Reality Show,USA
34,Prince Lorenzo,A charming and handsome prince who has recentl...,Opera,Italy
35,Signora Rosa,A mysterious and alluring woman who runs a loc...,Opera,Italy
36,Baron Gustavo,A wealthy and arrogant nobleman who loves to f...,Opera,Italy
37,Francesca,A fiery and passionate young woman who works a...,Opera,Italy
38,Don Carlo,A charming and charismatic young man who is of...,Opera,Italy
39,Duke Orsino,A pompous and self-important nobleman who is h...,Play,Ancient Greece
40,Lady Olivia,A wealthy and beautiful noblewoman who has rec...,Play,Ancient Greece
41,Sir Toby Belch,A drunken and lecherous knight who loves nothi...,Play,Ancient Greece
42,Malvolio,A pompous and self-righteous steward in Lady O...,Play,Ancient Greece
43,Viola,A plucky and resourceful young woman who is sh...,Play,Ancient Greece
44,Sir Andrew Aguecheek,A dim-witted and gullible nobleman who is brou...,Play,Ancient Greece
45,Bianca,Lady Olivia's cunning and quick-witted maid. B...,Play,Ancient Greece
46,Sebastian,"Viola's twin brother, who is also shipwrecked ...",Play,Ancient Greece
47,Feste,A jester and musician who works in Lady Olivia...,Play,Ancient Greece
48,Antonio,A sea captain who rescues Sebastian from the s...,Play,Ancient Greece
49,Abigail,A plucky and resourceful young woman who works...,Sitcom,USA
50,Thomas,A good-natured and affable young man who also ...,Sitcom,USA
51,Reverend Brown,The pious and stern minister of the local chur...,Sitcom,USA
52,Captain James,The charismatic and dashing captain of the loc...,Sitcom,USA
53,Mrs. Mercer,The matriarch of the wealthiest family in Will...,Sitcom,USA
54,Mr. Mercer,The bumbling and absent-minded patriarch of th...,Sitcom,USA

##### We will combine all the available information in single column called text consolidating all information with character description.
##### Column 'text' will used to create embeddings that will be used in formulation of RAG context

In [11]:
df_char['text'] = df_char.apply(lambda x: x['Name'] + " is a character in show type  " + x['Medium'] + " which is shot in location of " + x['Setting'] + ". " + x['Name'] + " is " + x['Description'], axis=1)

In [12]:
df_char['text'].iloc[0]

"Emily is a character in show type  Play which is shot in location of England. Emily is A young woman in her early 20s, Emily is an aspiring actress and Alice's daughter. She has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George."

In [13]:
df_char['text'].iloc[2]

"Alice is a character in show type  Play which is shot in location of England. Alice is A woman in her late 30s, Alice is a warm and nurturing mother of two, including Emily. She's kind-hearted and empathetic, but can be overly protective of her children and prone to worrying. She's married to Jack."

In [14]:
df_char['text'].iloc[1]

"Jack is a character in show type  Play which is shot in location of England. Jack is A middle-aged man in his 40s, Jack is a successful businessman and Sarah's boss. He has a no-nonsense attitude, but is fiercely loyal to his friends and family. He's married to Alice."

In [15]:
df_char[df_char['Name'] == "Sarah"]['text'].iloc[0]

"Sarah is a character in show type  Play which is shot in location of England. Sarah is A woman in her mid-20s, Sarah is a free-spirited artist and Jack's employee. She's creative, unconventional, and passionate about her work. However, she can also be flighty and impulsive at times."

In [16]:
df_char['text'].iloc[6]

"Rachel is a character in show type  Play which is shot in location of England. Rachel is A woman in her late 20s, Rachel is a shy and introverted librarian who is in a relationship with Tom. She's intelligent, thoughtful, and has a deep love of books. However, she struggles with social anxiety and often feels like an outsider."

In [17]:
df_char['text'].iloc[7]

"John is a character in show type  Play which is shot in location of England. John is A man in his 60s, John is a retired professor and Tom's father. He has a dry wit and a love of intellectual debate, but can also be stubborn and set in his ways."

In [18]:
##Setting embedding model, batch size
emb_model = "text-embedding-ada-002"
bs = 5
embeds= []
ds = len(df_char)
emb_model, bs, embeds, ds

('text-embedding-ada-002', 5, [], 55)

In [19]:
# let us create embeddings

for i in range(0, ds, bs):
    resp = openai.Embedding.create(
        input=df_char['text'].iloc[i:i+bs].tolist(),
        engine=emb_model
    )
    for data in resp['data']:
        data_emb = data['embedding']
        embeds.append(data_emb)

In [20]:
len(embeds)

55

In [21]:
len(embeds[0])

1536

In [22]:
df_char['embeds'] = embeds
df_char

,Name,Description,Medium,Setting,text,embeds
0,Emily,"A young woman in her early 20s, Emily is an as...",Play,England,Emily is a character in show type Play which ...,"[-0.014007964171469212, -0.008090022020041943,..."
1,Jack,"A middle-aged man in his 40s, Jack is a succes...",Play,England,Jack is a character in show type Play which i...,"[0.008103594183921814, -0.023805538192391396, ..."
2,Alice,"A woman in her late 30s, Alice is a warm and n...",Play,England,Alice is a character in show type Play which ...,"[0.011090533807873726, -0.0068944720551371574,..."
3,Tom,"A man in his 50s, Tom is a retired soldier and...",Play,England,Tom is a character in show type Play which is...,"[0.01612371765077114, -0.014847366139292717, 0..."
4,Sarah,"A woman in her mid-20s, Sarah is a free-spirit...",Play,England,Sarah is a character in show type Play which ...,"[-0.006663069594651461, -0.022750362753868103,..."
5,George,"A man in his early 30s, George is a charming a...",Play,England,George is a character in show type Play which...,"[-0.010464967228472233, -0.008763831108808517,..."
6,Rachel,"A woman in her late 20s, Rachel is a shy and i...",Play,England,Rachel is a character in show type Play which...,"[0.00021629472030326724, -0.011215937323868275..."
7,John,"A man in his 60s, John is a retired professor ...",Play,England,John is a character in show type Play which i...,"[0.01777494139969349, -0.01825176551938057, -0..."
8,Maria,"A middle-aged Latina woman in her 40s, Maria i...",Movie,Texas,Maria is a character in show type Movie which...,"[-0.007858765311539173, -0.01962009072303772, ..."
9,Caleb,"A young African American man in his early 20s,...",Movie,Texas,Caleb is a character in show type Movie which...,"[0.010566802695393562, -0.0329563245177269, 0...."
10,Tyler,"A white man in his mid-30s, Tyler is a tough-a...",Movie,Texas,Tyler is a character in show type Movie which...,"[0.011089691892266273, -0.044621869921684265, ..."
11,Sonya,"A white woman in her late 20s, Sonya is a free...",Movie,Texas,Sonya is a character in show type Movie which...,"[0.005750637501478195, -0.024084551259875298, ..."
12,Manuel,"A middle-aged Hispanic man in his 50s, Manuel ...",Movie,Texas,Manuel is a character in show type Movie whic...,"[-0.006857957690954208, -0.01836412400007248, ..."
13,Will,"A white man in his early 40s, Will is a succes...",Movie,Texas,Will is a character in show type Movie which ...,"[-0.0012741249520331621, -0.039022352546453476..."
14,Mia,"A young Australian woman in her mid-20s, Mia i...",Limited Series,Australia,Mia is a character in show type Limited Serie...,"[-0.006669442635029554, -0.02183210849761963, ..."
15,Lucas,"A middle-aged Australian man in his 40s, Lucas...",Limited Series,Australia,Lucas is a character in show type Limited Ser...,"[0.006499102339148521, -0.01558478269726038, -..."
16,Tahlia,A young Indigenous Australian woman in her ear...,Limited Series,Australia,Tahlia is a character in show type Limited Se...,"[-0.009942259639501572, -0.011854232288897038,..."
17,Max,"A white Australian man in his late 20s, Max is...",Limited Series,Australia,Max is a character in show type Limited Serie...,"[0.003965550102293491, -0.03276585787534714, -..."
18,Ava,"A middle-aged Australian woman in her 50s, Ava...",Limited Series,Australia,Ava is a character in show type Limited Serie...,"[0.0031945800874382257, -0.01639583520591259, ..."
19,Donna,A seasoned performer with a larger-than-life p...,Musical,USA,Donna is a character in show type Musical whi...,"[-0.02532845549285412, -0.01963815465569496, 0..."
20,Johnny,"A young up-and-coming performer, Johnny is ful...",Musical,USA,Johnny is a character in show type Musical wh...,"[-0.022671421989798546, -0.018853897228837013,..."
21,Sable,"A sultry and dramatic performer, Sable exudes ...",Musical,USA,Sable is a character in show type Musical whi...,"[-0.024361371994018555, -0.018106605857610703,..."
22,Dolly,"A bubbly and vivacious performer, Dolly is a f...",Musical,USA,Dolly is a character in show type Musical whi...,"[-0.03215302154421806, -0.023510584607720375, ..."
23,Vixen,"A fierce and competitive performer, Vixen is a...",Musical,USA,Vixen is a character in show type Musical whi...,"[-0.027203256264328957, -0.02892834134399891, ..."
24,Karma,"A chameleon-like performer, Karma is known for...",Musical,USA,Karma is a character in show type Musical whi...,"[0.004204113502055407, -0.023305626586079597, ..."
25,Crystal,"A quirky and imaginative performer, Crystal is...",Musical,USA,Crystal is a character in show type Musical w...,"[0.0005727222887799144, -0.019027933478355408,..."
26,Olivia,A confident and charismatic marketing executiv...,Reality Show,USA,Olivia is a character in show type Reality Sh...,"[-0.0030850840266793966, -0.012121512554585934..."
27,Marcus,"A charming and successful entrepreneur, Marcus...",Reality Show,USA,Marcus is a character in show type Reality Sh...,"[-0.0008901737746782601, -0.036256738007068634..."
28,Maya,A kind and compassionate nurse with a heart of...,Reality Show,USA,Maya is a character in show type Reality Show...,"[-0.021779365837574005, -0.017254827544093132,..."
29,James,"A handsome and athletic personal trainer, Jame...",Reality Show,USA,James is a character in show type Reality Sho...,"[-0.017441654577851295, -0.005861861631274223,..."
30,Sophia,"A fun-loving and adventurous travel blogger, S...",Reality Show,USA,Sophia is a character in show type Reality Sh...,"[0.021469252184033394, -0.013852427713572979, ..."
31,Noah,"A quirky and creative graphic designer, Noah i...",Reality Show,USA,Noah is a character in show type Reality Show...,"[-0.012487961910665035, -0.021337488666176796,..."
32,Chloe,"A driven and ambitious attorney, Chloe is alwa...",Reality Show,USA,Chloe is a character in show type Reality Sho...,"[0.0026951839681714773, -0.0050859940238296986..."
33,Jake,"A laid-back and easygoing firefighter, Jake is...",Reality Show,USA,Jake is a character in show type Reality Show...,"[-0.01039772480726242, -0.017671557143330574, ..."
34,Prince Lorenzo,A charming and handsome prince who has recentl...,Opera,Italy,Prince Lorenzo is a character in show type Op...,"[0.0038650508504360914, -0.020196720957756042,..."
35,Signora Rosa,A mysterious and alluring woman who runs a loc...,Opera,Italy,Signora Rosa is a character in show type Oper...,"[0.010555709712207317, -0.017059732228517532, ..."
36,Baron Gustavo,A wealthy and arrogant nobleman who loves to f...,Opera,Italy,Baron Gustavo is a character in show type Ope...,"[-0.012145297601819038, -0.02202257700264454, ..."
37,Francesca,A fiery and passionate young woman who works a...,Opera,Italy,Francesca is a character in show type Opera w...,"[-0.008682961575686932, -0.01879451610147953, ..."
38,Don Carlo,A charming and charismatic young man who is of...,Opera,Italy,Don Carlo is a character in show type Opera w...,"[-0.004638032056391239, -0.013348317705094814,..."
39,Duke Orsino,A pompous and self-important nobleman who is h...,Play,Ancient Greece,Duke Orsino is a character in show type Play ...,"[-0.0031075007282197475, -0.04345935955643654,..."
40,Lady Olivia,A wealthy and beautiful noblewoman who has rec...,Play,Ancient Greece,Lady Olivia is a character in show type Play ...,"[-0.012530873529613018, -0.023169301450252533,..."
41,Sir Toby Belch,A drunken and lecherous knight who loves nothi...,Play,Ancient Greece,Sir Toby Belch is a character in show type Pl...,"[0.0010373031254857779, -0.02914188802242279, ..."
42,Malvolio,A pompous and self-righteous steward in Lady O...,Play,Ancient Greece,Malvolio is a character in show type Play whi...,"[-0.012843060307204723, -0.03144492954015732, ..."
43,Viola,A plucky and resourceful young woman who is sh...,Play,Ancient Greece,Viola is a character in show type Play which ...,"[-0.006594130769371986, -0.039467670023441315,..."
44,Sir Andrew Aguecheek,A dim-witted and gullible nobleman who is brou...,Play,Ancient Greece,Sir Andrew Aguecheek is a character in show ty...,"[-0.012175093404948711, -0.022184230387210846,..."
45,Bianca,Lady Olivia's cunning and quick-witted maid. B...,Play,Ancient Greece,Bianca is a character in show type Play which...,"[-0.008880579844117165, -0.02432820200920105, ..."
46,Sebastian,"Viola's twin brother, who is also shipwrecked ...",Play,Ancient Greece,Sebastian is a character in show type Play wh...,"[-0.004746768623590469, -0.037896543741226196,..."
47,Feste,A jester and musician who works in Lady Olivia...,Play,Ancient Greece,Feste is a character in show type Play which ...,"[-0.008371424861252308, -0.020560219883918762,..."
48,Antonio,A sea captain who rescues Sebastian from the s...,Play,Ancient Greece,Antonio is a character in show type Play whic...,"[-0.003480290062725544, -0.029492631554603577,..."
49,Abigail,A plucky and resourceful young woman who works...,Sitcom,USA,Abigail is a character in show type Sitcom wh...,"[-0.019153211265802383, -0.02193649485707283, ..."
50,Thomas,A good-natured and affable young man who also ...,Sitcom,USA,Thomas is a character in show type Sitcom whi...,"[-0.006552612874656916, -0.003821263089776039,..."
51,Reverend Brown,The pious and stern minister of the local chur...,Sitcom,USA,Reverend Brown is a character in show type Si...,"[0.0014002053067088127, -0.030203143134713173,..."
52,Captain James,The charismatic and dashing captain of the loc...,Sitcom,USA,Captain James is a character in show type Sit...,"[0.0012831651838496327, -0.02309204824268818, ..."
53,Mrs. Mercer,The matriarch of the wealthiest family in Will...,Sitcom,USA,Mrs. Mercer is a character in show type Sitco...,"[-0.00986770261079073, -0.0073179942555725574,..."
54,Mr. Mercer,The bumbling and absent-minded patriarch of th...,Sitcom,USA,Mr. Mercer is a character in show type Sitcom...,"[0.0037510229740291834, -0.015109199099242687,..."

In [23]:
df_char.to_csv('./char_proj.csv')

## Custom Query Completion

TODO: In the cells below, compose a custom query using your chosen dataset and retrieve results from an OpenAI `Completion` model. You may copy and paste any useful code from the course materials.

In [24]:
## we will use the following 3 questions in this project:
##1)"Who is Emily?"
##2)"How are Alice, Jack and Emily related?"
##3)"What are the names of 8 characters in show type Play shot in England?"

In [25]:
q1 = "Who is Emily?"
q2 = "How are Alice, Jack and Emily related?"
q3 = "What are the names of 8 characters in show type Play shot in England?"
q1,q2,q3

('Who is Emily?',
 'How are Alice, Jack and Emily related?',
 'What are the names of 8 characters in show type Play shot in England?')

In [26]:
def create_q_embed(q):
    question = q
    q_emb = openai.Embedding.create(
        engine=emb_model,
        input=question
        )
    return q_emb['data'][0]['embedding']

In [27]:
q1_emb = create_q_embed(q1)
q2_emb = create_q_embed(q2)
q3_emb = create_q_embed(q3)

In [28]:
len(q1_emb), type(q1_emb), len(q2_emb), type(q2_emb), len(q3_emb), type(q3_emb)

(1536, list, 1536, list, 1536, list)

In [29]:
from openai.embeddings_utils import get_embedding, distances_from_embeddings

In [30]:
# Let us calculate cosine distance of question embeddings from different embeddings present in text column of dataframe
def calc_cos_dist(q_emb):
    cos_dist = distances_from_embeddings(q_emb,
                                         df_char['embeds'].values,
                                         distance_metric="cosine"
                                         )
    return cos_dist
#type(cos_dist), len(cos_dist)

In [31]:
q1_cos_dist = calc_cos_dist(q1_emb)
q2_cos_dist = calc_cos_dist(q2_emb)
q3_cos_dist = calc_cos_dist(q3_emb)

In [32]:
type(q1_cos_dist), len(q1_cos_dist), type(q2_cos_dist), len(q2_cos_dist), type(q3_cos_dist), len(q3_cos_dist)

(list, 55, list, 55, list, 55)

In [33]:
df_char['q1_cos_dist'] = q1_cos_dist
df_char['q2_cos_dist'] = q2_cos_dist
df_char['q3_cos_dist'] = q3_cos_dist

In [34]:
df_char

,Name,Description,Medium,Setting,text,embeds,q1_cos_dist,q2_cos_dist,q3_cos_dist
0,Emily,"A young woman in her early 20s, Emily is an as...",Play,England,Emily is a character in show type Play which ...,"[-0.014007964171469212, -0.008090022020041943,...",0.117426,0.177256,0.182400
1,Jack,"A middle-aged man in his 40s, Jack is a succes...",Play,England,Jack is a character in show type Play which i...,"[0.008103594183921814, -0.023805538192391396, ...",0.243633,0.189879,0.174346
2,Alice,"A woman in her late 30s, Alice is a warm and n...",Play,England,Alice is a character in show type Play which ...,"[0.011090533807873726, -0.0068944720551371574,...",0.180261,0.151564,0.183976
3,Tom,"A man in his 50s, Tom is a retired soldier and...",Play,England,Tom is a character in show type Play which is...,"[0.01612371765077114, -0.014847366139292717, 0...",0.237824,0.255482,0.198132
4,Sarah,"A woman in her mid-20s, Sarah is a free-spirit...",Play,England,Sarah is a character in show type Play which ...,"[-0.006663069594651461, -0.022750362753868103,...",0.223287,0.234086,0.176460
5,George,"A man in his early 30s, George is a charming a...",Play,England,George is a character in show type Play which...,"[-0.010464967228472233, -0.008763831108808517,...",0.204115,0.241372,0.185308
6,Rachel,"A woman in her late 20s, Rachel is a shy and i...",Play,England,Rachel is a character in show type Play which...,"[0.00021629472030326724, -0.011215937323868275...",0.217207,0.251718,0.199804
7,John,"A man in his 60s, John is a retired professor ...",Play,England,John is a character in show type Play which i...,"[0.01777494139969349, -0.01825176551938057, -0...",0.256561,0.251161,0.188895
8,Maria,"A middle-aged Latina woman in her 40s, Maria i...",Movie,Texas,Maria is a character in show type Movie which...,"[-0.007858765311539173, -0.01962009072303772, ...",0.248914,0.260889,0.236210
9,Caleb,"A young African American man in his early 20s,...",Movie,Texas,Caleb is a character in show type Movie which...,"[0.010566802695393562, -0.0329563245177269, 0....",0.277489,0.285446,0.253314
10,Tyler,"A white man in his mid-30s, Tyler is a tough-a...",Movie,Texas,Tyler is a character in show type Movie which...,"[0.011089691892266273, -0.044621869921684265, ...",0.267981,0.276117,0.254147
11,Sonya,"A white woman in her late 20s, Sonya is a free...",Movie,Texas,Sonya is a character in show type Movie which...,"[0.005750637501478195, -0.024084551259875298, ...",0.255731,0.276692,0.246526
12,Manuel,"A middle-aged Hispanic man in his 50s, Manuel ...",Movie,Texas,Manuel is a character in show type Movie whic...,"[-0.006857957690954208, -0.01836412400007248, ...",0.295395,0.285130,0.248586
13,Will,"A white man in his early 40s, Will is a succes...",Movie,Texas,Will is a character in show type Movie which ...,"[-0.0012741249520331621, -0.039022352546453476...",0.282622,0.272827,0.244212
14,Mia,"A young Australian woman in her mid-20s, Mia i...",Limited Series,Australia,Mia is a character in show type Limited Serie...,"[-0.006669442635029554, -0.02183210849761963, ...",0.233317,0.272051,0.244903
15,Lucas,"A middle-aged Australian man in his 40s, Lucas...",Limited Series,Australia,Lucas is a character in show type Limited Ser...,"[0.006499102339148521, -0.01558478269726038, -...",0.273202,0.269785,0.239177
16,Tahlia,A young Indigenous Australian woman in her ear...,Limited Series,Australia,Tahlia is a character in show type Limited Se...,"[-0.009942259639501572, -0.011854232288897038,...",0.242036,0.263792,0.265327
17,Max,"A white Australian man in his late 20s, Max is...",Limited Series,Australia,Max is a character in show type Limited Serie...,"[0.003965550102293491, -0.03276585787534714, -...",0.270111,0.273497,0.246621
18,Ava,"A middle-aged Australian woman in her 50s, Ava...",Limited Series,Australia,Ava is a character in show type Limited Serie...,"[0.0031945800874382257, -0.01639583520591259, ...",0.231713,0.258135,0.246543
19,Donna,A seasoned performer with a larger-than-life p...,Musical,USA,Donna is a character in show type Musical whi...,"[-0.02532845549285412, -0.01963815465569496, 0...",0.283652,0.291823,0.247458
20,Johnny,"A young up-and-coming performer, Johnny is ful...",Musical,USA,Johnny is a character in show type Musical wh...,"[-0.022671421989798546, -0.018853897228837013,...",0.270395,0.273657,0.237188
21,Sable,"A sultry and dramatic performer, Sable exudes ...",Musical,USA,Sable is a character in show type Musical whi...,"[-0.024361371994018555, -0.018106605857610703,...",0.277096,0.288159,0.240796
22,Dolly,"A bubbly and vivacious performer, Dolly is a f...",Musical,USA,Dolly is a character in show type Musical whi...,"[-0.03215302154421806, -0.023510584607720375, ...",0.254562,0.265620,0.231097
23,Vixen,"A fierce and competitive performer, Vixen is a...",Musical,USA,Vixen is a character in show type Musical whi...,"[-0.027203256264328957, -0.02892834134399891, ...",0.269921,0.294939,0.245210
24,Karma,"A chameleon-like performer, Karma is known for...",Musical,USA,Karma is a character in show type Musical whi...,"[0.004204113502055407, -0.023305626586079597, ...",0.257220,0.278150,0.231796
25,Crystal,"A quirky and imaginative performer, Crystal is...",Musical,USA,Crystal is a character in show type Musical w...,"[0.0005727222887799144, -0.019027933478355408,...",0.265223,0.280659,0.228197
26,Olivia,A confident and charismatic marketing executiv...,Reality Show,USA,Olivia is a character in show type Reality Sh...,"[-0.0030850840266793966, -0.012121512554585934...",0.227110,0.273115,0.251785
27,Marcus,"A charming and successful entrepreneur, Marcus...",Reality Show,USA,Marcus is a character in show type Reality Sh...,"[-0.0008901737746782601, -0.036256738007068634...",0.290388,0.309540,0.245749
28,Maya,A kind and compassionate nurse with a heart of...,Reality Show,USA,Maya is a character in show type Reality Show...,"[-0.021779365837574005, -0.017254827544093132,...",0.249901,0.287146,0.250378
29,James,"A handsome and athletic personal trainer, Jame...",Reality Show,USA,James is a character in show type Reality Sho...,"[-0.017441654577851295, -0.005861861631274223,...",0.267994,0.293277,0.245941
30,Sophia,"A fun-loving and adventurous travel blogger, S...",Reality Show,USA,Sophia is a character in show type Reality Sh...,"[0.021469252184033394, -0.013852427713572979, ...",0.229469,0.280319,0.240810
31,Noah,"A quirky and creative graphic designer, Noah i...",Reality Show,USA,Noah is a character in show type Reality Show...,"[-0.012487961910665035, -0.021337488666176796,...",0.275471,0.296534,0.250522
32,Chloe,"A driven and ambitious attorney, Chloe is alwa...",Reality Show,USA,Chloe is a character in show type Reality Sho...,"[0.0026951839681714773, -0.0050859940238296986...",0.242399,0.280680,0.238983
33,Jake,"A laid-back and easygoing firefighter, Jake is...",Reality Show,USA,Jake is a character in show type Reality Show...,"[-0.01039772480726242, -0.017671557143330574, ...",0.236525,0.248108,0.249049
34,Prince Lorenzo,A charming and handsome prince who has recentl...,Opera,Italy,Prince Lorenzo is a character in show type Op...,"[0.0038650508504360914, -0.020196720957756042,...",0.303495,0.294561,0.234871
35,Signora Rosa,A mysterious and alluring woman who runs a loc...,Opera,Italy,Signora Rosa is a character in show type Oper...,"[0.010555709712207317, -0.017059732228517532, ...",0.270279,0.299832,0.244440
36,Baron Gustavo,A wealthy and arrogant nobleman who loves to f...,Opera,Italy,Baron Gustavo is a character in show type Ope...,"[-0.012145297601819038, -0.02202257700264454, ...",0.303004,0.318772,0.240665
37,Francesca,A fiery and passionate young woman who works a...,Opera,Italy,Francesca is a character in show type Opera w...,"[-0.008682961575686932, -0.01879451610147953, ...",0.266025,0.290617,0.235238
38,Don Carlo,A charming and charismatic young man who is of...,Opera,Italy,Don Carlo is a character in show type Opera w...,"[-0.004638032056391239, -0.013348317705094814,...",0.305403,0.298026,0.237203
39,Duke Orsino,A pompous and self-important nobleman who is h...,Play,Ancient Greece,Duke Orsino is a character in show type Play ...,"[-0.0031075007282197475, -0.04345935955643654,...",0.272563,0.276332,0.215055
40,Lady Olivia,A wealthy and beautiful noblewoman who has rec...,Play,Ancient Greece,Lady Olivia is a character in show type Play ...,"[-0.012530873529613018, -0.023169301450252533,...",0.235806,0.245257,0.209622
41,Sir Toby Belch,A drunken and lecherous knight who loves nothi...,Play,Ancient Greece,Sir Toby Belch is a character in show type Pl...,"[0.0010373031254857779, -0.02914188802242279, ...",0.290844,0.278104,0.200727
42,Malvolio,A pompous and self-righteous steward in Lady O...,Play,Ancient Greece,Malvolio is a character in show type Play whi...,"[-0.012843060307204723, -0.03144492954015732, ...",0.261514,0.273120,0.213446
43,Viola,A plucky and resourceful young woman who is sh...,Play,Ancient Greece,Viola is a character in show type Play which ...,"[-0.006594130769371986, -0.039467670023441315,...",0.252976,0.271823,0.224656
44,Sir Andrew Aguecheek,A dim-witted and gullible nobleman who is brou...,Play,Ancient Greece,Sir Andrew Aguecheek is a character in show ty...,"[-0.012175093404948711, -0.022184230387210846,...",0.293919,0.280674,0.205288
45,Bianca,Lady Olivia's cunning and quick-witted maid. B...,Play,Ancient Greece,Bianca is a character in show type Play which...,"[-0.008880579844117165, -0.02432820200920105, ...",0.256022,0.252328,0.215796
46,Sebastian,"Viola's twin brother, who is also shipwrecked ...",Play,Ancient Greece,Sebastian is a character in show type Play wh...,"[-0.004746768623590469, -0.037896543741226196,...",0.281145,0.273139,0.237347
47,Feste,A jester and musician who works in Lady Olivia...,Play,Ancient Greece,Feste is a character in show type Play which ...,"[-0.008371424861252308, -0.020560219883918762,...",0.271266,0.274365,0.227311
48,Antonio,A sea captain who rescues Sebastian from the s...,Play,Ancient Greece,Antonio is a character in show type Play whic...,"[-0.003480290062725544, -0.029492631554603577,...",0.301298,0.288098,0.234051
49,Abigail,A plucky and resourceful young woman who works...,Sitcom,USA,Abigail is a character in show type Sitcom wh...,"[-0.019153211265802383, -0.02193649485707283, ...",0.227559,0.254819,0.230084
50,Thomas,A good-natured and affable young man who also ...,Sitcom,USA,Thomas is a character in show type Sitcom whi...,"[-0.006552612874656916, -0.003821263089776039,...",0.251282,0.256880,0.225797
51,Reverend Brown,The pious and stern minister of the local chur...,Sitcom,USA,Reverend Brown is a character in show type Si...,"[0.0014002053067088127, -0.030203143134713173,...",0.271208,0.287845,0.236242
52,Captain James,The charismatic and dashing captain of the loc...,Sitcom,USA,Captain James is a character in show type Sit...,"[0.0012831651838496327, -0.02309204824268818, ...",0.268848,0.268983,0.213411
53,Mrs. Mercer,The matriarch of the wealthiest family in Will...,Sitcom,USA,Mrs. Mercer is a character in show type Sitco...,"[-0.00986770261079073, -0.0073179942555725574,...",0.252308,0.270450,0.243999
54,Mr. Mercer,The bumbling and absent-minded patriarch of th...,Sitcom,USA,Mr. Mercer is a character in show type Sitcom...,"[0.0037510229740291834, -0.015109199099242687,...",0.290284,0.285814,0.241725

In [35]:
#df_char.sort_values(by="cd", ascending=True, inplace=True)
#df_char

In [36]:
df_char[df_char['Setting']=='England']

,Name,Description,Medium,Setting,text,embeds,q1_cos_dist,q2_cos_dist,q3_cos_dist
0,Emily,"A young woman in her early 20s, Emily is an as...",Play,England,Emily is a character in show type Play which ...,"[-0.014007964171469212, -0.008090022020041943,...",0.117426,0.177256,0.182400
1,Jack,"A middle-aged man in his 40s, Jack is a succes...",Play,England,Jack is a character in show type Play which i...,"[0.008103594183921814, -0.023805538192391396, ...",0.243633,0.189879,0.174346
2,Alice,"A woman in her late 30s, Alice is a warm and n...",Play,England,Alice is a character in show type Play which ...,"[0.011090533807873726, -0.0068944720551371574,...",0.180261,0.151564,0.183976
3,Tom,"A man in his 50s, Tom is a retired soldier and...",Play,England,Tom is a character in show type Play which is...,"[0.01612371765077114, -0.014847366139292717, 0...",0.237824,0.255482,0.198132
4,Sarah,"A woman in her mid-20s, Sarah is a free-spirit...",Play,England,Sarah is a character in show type Play which ...,"[-0.006663069594651461, -0.022750362753868103,...",0.223287,0.234086,0.176460
5,George,"A man in his early 30s, George is a charming a...",Play,England,George is a character in show type Play which...,"[-0.010464967228472233, -0.008763831108808517,...",0.204115,0.241372,0.185308
6,Rachel,"A woman in her late 20s, Rachel is a shy and i...",Play,England,Rachel is a character in show type Play which...,"[0.00021629472030326724, -0.011215937323868275...",0.217207,0.251718,0.199804
7,John,"A man in his 60s, John is a retired professor ...",Play,England,John is a character in show type Play which i...,"[0.01777494139969349, -0.01825176551938057, -0...",0.256561,0.251161,0.188895

In [37]:
len(df_char[df_char['Setting']=='England'])

8

In [38]:
df_char[df_char['Setting']=='England']['Name'].tolist()

['Emily', 'Jack', 'Alice', 'Tom', 'Sarah', 'George', 'Rachel', 'John']

In [39]:
basic_prompt_template = """
Question: {}
Answer:
"""

print(basic_prompt_template)

Question: {}
Answer:

In [40]:
prompt_template = """
Answer the question based on the context below, and if the question cannot be answered based on the context, say "I don't know"

Context:

{}

---

Question: {}
Answer:"""

print(prompt_template)

Answer the question based on the context below, and if the question cannot be answered based on the context, say "I don't know"

Context:

{}

---

Question: {}
Answer:

In [41]:
import tiktoken

In [42]:
tokenizer = tiktoken.get_encoding("cl100k_base")
tokenizer

In [43]:
def create_prompt(df, question, prompt_template, q_cos_dist):
    q_len = len(tokenizer.encode(question))
    p_len = len(tokenizer.encode(prompt_template))
    ans_len = 400
    total_len = 4000
    thr_len = total_len - (q_len+p_len+ans_len)
    df_sort_q = df.sort_values(by=q_cos_dist, ascending=True)
    text_values = df_sort_q['text'].values
    cont_len = 0
    embeds = []
    for text in text_values:
        text_len = len(tokenizer.encode(text))
        cont_len += text_len
        embeds.append(text)
        if cont_len >= thr_len:
            break
    embeds_pp = "\n\n##\n\n".join(embeds)
    prompt = prompt_template.format(embeds_pp, question)
    return prompt

In [44]:
prompt_q1 = create_prompt(df_char, q1, prompt_template, "q1_cos_dist")
prompt_q2 = create_prompt(df_char, q2, prompt_template, "q2_cos_dist")
prompt_q3 = create_prompt(df_char, q3, prompt_template, "q3_cos_dist")

In [45]:
print(prompt_q1)

Answer the question based on the context below, and if the question cannot be answered based on the context, say "I don't know"

Context:

Emily is a character in show type  Play which is shot in location of England. Emily is A young woman in her early 20s, Emily is an aspiring actress and Alice's daughter. She has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George.

##

Alice is a character in show type  Play which is shot in location of England. Alice is A woman in her late 30s, Alice is a warm and nurturing mother of two, including Emily. She's kind-hearted and empathetic, but can be overly protective of her children and prone to worrying. She's married to Jack.

##

George is a character in show type  Play which is shot in location of England. George is A man in his early 30s, George is a charming and charismatic businessman who is in a relationship with Emily. He's ambitious, confident, and always looking for the next big opportunity. However, he's also prone to bending the rules to get what he wants.

##

Rachel is a character in show type  Play which is shot in location of England. Rachel is A woman in her late 20s, Rachel is a shy and introverted librarian who is in a relationship with Tom. She's intelligent, thoughtful, and has a deep love of books. However, she struggles with social anxiety and often feels like an outsider.

##

Sarah is a character in show type  Play which is shot in location of England. Sarah is A woman in her mid-20s, Sarah is a free-spirited artist and Jack's employee. She's creative, unconventional, and passionate about her work. However, she can also be flighty and impulsive at times.

##

Olivia is a character in show type  Reality Show which is shot in location of USA. Olivia is A confident and charismatic marketing executive with a heart of gold. Olivia is always the life of the party, and her infectious personality draws people to her. She's looking for someone who can keep up with her high energy and bring some stability to her life.

##

Abigail is a character in show type  Sitcom which is shot in location of USA. Abigail is A plucky and resourceful young woman who works as a maid in one of the taverns in colonial Williamsburg. Abigail is hard-working and determined, and dreams of one day owning her own business. She has a friendly rivalry with her co-worker, Thomas.

##

Sophia is a character in show type  Reality Show which is shot in location of USA. Sophia is A fun-loving and adventurous travel blogger, Sophia is always looking for her next big adventure. She's looking for someone who can join her on her travels and share in her love of exploration. She's a free spirit who isn't afraid to take risks and try new things.

##

Ava is a character in show type  Limited Series which is shot in location of Australia. Ava is A middle-aged Australian woman in her 50s, Ava is a successful fashion designer who's built an empire on her impeccable taste and attention to detail. She's elegant, sophisticated, and always knows what's in style. She's married to Lucas, but their marriage is strained due to his infidelity. She's also been a mentor to Tahlia, and has helped her navigate the art world.

##

Mia is a character in show type  Limited Series which is shot in location of Australia. Mia is A young Australian woman in her mid-20s, Mia is a driven and ambitious lawyer who's just landed her dream job at a top law firm in Sydney. She's the younger sister of Max, a former soldier who's struggling with PTSD, and is trying to help him navigate his challenges while also balancing her demanding career.

##

Lady Olivia is a character in show type  Play which is shot in location of Ancient Greece. Lady Olivia is A wealthy and beautiful noblewoman who has recently become a widow. Lady Olivia is melancholy and withdrawn, and refuses to entertain any suitors. She is the object of Duke Orsino's affections, but is not interested in him. She is also the cousin of Sir Toby Belch and his niece.

##

Jake is a character in show type  Reality Show which is shot in location of USA. Jake is A laid-back and easygoing firefighter, Jake is the quintessential good guy. He's looking for someone who shares his values of honesty and integrity, and who is looking for a stable and committed relationship. He's a bit of a hopeless romantic, and is always looking for ways to sweep his partner off their feet.

##

Tom is a character in show type  Play which is shot in location of England. Tom is A man in his 50s, Tom is a retired soldier and John's son. He has a no-nonsense approach to life, but is haunted by his experiences in combat and struggles with PTSD. He's also in a relationship with Rachel.

##

Tahlia is a character in show type  Limited Series which is shot in location of Australia. Tahlia is A young Indigenous Australian woman in her early 20s, Tahlia is a talented artist who's just been accepted into a prestigious art school. She's the niece of Mia and Max, and they've been like siblings since they were young. She's struggling to find her place in the world as an Indigenous woman, but Mia and Max are always there to support her.

##

Chloe is a character in show type  Reality Show which is shot in location of USA. Chloe is A driven and ambitious attorney, Chloe is always striving for success. She's looking for someone who can match her intellect and drive, and who is supportive of her career goals. She's a bit guarded when it comes to matters of the heart, but is ready to let her guard down for the right person.

##

Jack is a character in show type  Play which is shot in location of England. Jack is A middle-aged man in his 40s, Jack is a successful businessman and Sarah's boss. He has a no-nonsense attitude, but is fiercely loyal to his friends and family. He's married to Alice.

##

Maria is a character in show type  Movie which is shot in location of Texas. Maria is A middle-aged Latina woman in her 40s, Maria is a hard-working single mother who owns a small family-run diner in a small Texas town. She's fiercely protective of her teenage daughter, Sofia, and is always trying to balance work and family.

##

Maya is a character in show type  Reality Show which is shot in location of USA. Maya is A kind and compassionate nurse with a heart of gold, Maya is always putting others before herself. She's looking for someone who shares her values and is committed to making the world a better place. She's not afraid to speak her mind and stand up for what she believes in.

##

Thomas is a character in show type  Sitcom which is shot in location of USA. Thomas is A good-natured and affable young man who also works in the same tavern as Abigail. Thomas is the jester of the group and enjoys making jokes and lightening the mood. He often finds himself caught up in Abigail's schemes.

##

Mrs. Mercer is a character in show type  Sitcom which is shot in location of USA. Mrs. Mercer is The matriarch of the wealthiest family in Williamsburg. Mrs. Mercer is a bit of a snob and enjoys reminding everyone of her social standing. She often hires Abigail to work in her home and is very demanding.

##

Viola is a character in show type  Play which is shot in location of Ancient Greece. Viola is A plucky and resourceful young woman who is shipwrecked on the coast of Illyria. Viola disguises herself as a man, taking on the identity of Cesario, and becomes a servant in Duke Orsino's household. She develops feelings for the Duke, but is unable to reveal her true identity.

##

Dolly is a character in show type  Musical which is shot in location of USA. Dolly is A bubbly and vivacious performer, Dolly is a fan favorite for her infectious personality and comedic performances. She's known for her campy looks and over-the-top antics, but can struggle with self-doubt and insecurity off stage. She's also a good friend of Johnny, often offering her words of encouragement.

##

Sonya is a character in show type  Movie which is shot in location of Texas. Sonya is A white woman in her late 20s, Sonya is a free-spirited journalist who's always on the hunt for the next big story. She's passionate, tenacious, and unafraid to speak her mind. However, she's also struggling to balance her career with her personal life, and has a tendency to push people away.

##

Bianca is a character in show type  Play which is shot in location of Ancient Greece. Bianca is Lady Olivia's cunning and quick-witted maid. Bianca is a master of mischief and pranks, and often collaborates with Sir Toby Belch to torment Malvolio. She is also secretly in love with Sir Toby.

##

John is a character in show type  Play which is shot in location of England. John is A man in his 60s, John is a retired professor and Tom's father. He has a dry wit and a love of intellectual debate, but can also be stubborn and set in his ways.

##

Karma is a character in show type  Musical which is shot in location of USA. Karma is A chameleon-like performer, Karma is known for her ability to transform herself into any character. She's a master of illusion and is always pushing boundaries with her looks and performances, but can sometimes struggle with authenticity and staying true to herself. She's also a friend of Dolly, often offering her a listening ear when she needs it.

##

Malvolio is a character in show type  Play which is shot in location of Ancient Greece. Malvolio is A pompous and self-righteous steward in Lady Olivia's household. Malvolio is humorless and uptight, and is often the target of Sir Toby Belch's pranks. He is secretly in love with Lady Olivia and harbors dreams of marrying her.

##

Crystal is a character in show type  Musical which is shot in location of USA. Crystal is A quirky and imaginative performer, Crystal is always surprising audiences with her off-beat performances and unconventional looks. She's known for her unique creativity and imaginative approach, but can sometimes struggle with staying focused and on task. She's also a bit of a wildcard, and the other performers never know what to expect from her.

##

Francesca is a character in show type  Opera which is shot in location of Italy. Francesca is A fiery and passionate young woman who works as a blacksmith. She is strong-willed and independent, and her singing voice is bold and powerful. Francesca has caught the eye of Prince Lorenzo, but she is hesitant to give her heart to a man who comes from such a different world.

##

Tyler is a character in show type  Movie which is shot in location of Texas. Tyler is A white man in his mid-30s, Tyler is a tough-as-nails sheriff who takes his job very seriously. He's stoic, no-nonsense, and has a strong sense of justice. However, he's also struggling to come to terms with a recent tragedy in his personal life.

##

James is a character in show type  Reality Show which is shot in location of USA. James is A handsome and athletic personal trainer, James is always up for a challenge. He's looking for someone who is as passionate about fitness as he is, and who can keep up with his intense workout regimen. He can sometimes come across as a bit too competitive, but his heart is always in the right place.

##

Captain James is a character in show type  Sitcom which is shot in location of USA. Captain James is The charismatic and dashing captain of the local militia. Captain James is a ladies' man and enjoys flirting with the women of the town. He has a friendly rivalry with Reverend Brown and often teases him about his piousness.

##

Vixen is a character in show type  Musical which is shot in location of USA. Vixen is A fierce and competitive performer, Vixen is always out to win. She's known for her aggressive lip-syncing style and high-energy performances, but can be confrontational and difficult to work with. She's also a rival of Sable, and the two often clash both on and off stage.

##

Max is a character in show type  Limited Series which is shot in location of Australia. Max is A white Australian man in his late 20s, Max is a former soldier who's struggling to adjust to civilian life after serving in Afghanistan. He's tough, no-nonsense, and has a strong sense of duty. He's the older brother of Mia, and they've always been close. He's also Ava's godson, and she's always been like a second mother to him.

##

Signora Rosa is a character in show type  Opera which is shot in location of Italy. Signora Rosa is A mysterious and alluring woman who runs a local apothecary. Signora Rosa is known for her beauty and her magical remedies, which some believe have mystical powers. Her singing voice is hauntingly beautiful and her demeanor is both captivating and enigmatic.

##

Johnny is a character in show type  Musical which is shot in location of USA. Johnny is A young up-and-coming performer, Johnny is full of energy and enthusiasm. She's known for her edgy and unconventional looks, but can be a bit scatterbrained at times. She looks up to Donna as a mentor and hopes to follow in her footsteps.

##

Reverend Brown is a character in show type  Sitcom which is shot in location of USA. Reverend Brown is The pious and stern minister of the local church. Reverend Brown takes his role very seriously and often clashes with the more irreverent characters in the town. He is also secretly in love with Abigail and tries to win her over with his piety.

##

Feste is a character in show type  Play which is shot in location of Ancient Greece. Feste is A jester and musician who works in Lady Olivia's household. Feste is the wisest character in the play, and uses his wit and intelligence to comment on the actions of the other characters. He is also a confidant to Viola, and helps her navigate her complicated situation.

##

Duke Orsino is a character in show type  Play which is shot in location of Ancient Greece. Duke Orsino is A pompous and self-important nobleman who is hopelessly in love with Lady Olivia. Duke Orsino is arrogant and condescending to those around him, but is also a bit of a buffoon. He is related to Sir Toby Belch, who is his uncle.

##

Lucas is a character in show type  Limited Series which is shot in location of Australia. Lucas is A middle-aged Australian man in his 40s, Lucas is a successful businessman and the CEO of a major tech company. He's charming, charismatic, and has a way with people. He's been married to Ava, a successful fashion designer, for many years, but their marriage is on the rocks due to his infidelity.

##

Noah is a character in show type  Reality Show which is shot in location of USA. Noah is A quirky and creative graphic designer, Noah is always pushing the boundaries with his art. He's looking for someone who can appreciate his unique perspective and isn't afraid to be a little unconventional. He's a bit of a romantic at heart, and loves nothing more than creating grand gestures of love for the people he cares about.

##

Sable is a character in show type  Musical which is shot in location of USA. Sable is A sultry and dramatic performer, Sable exudes confidence on stage. She's known for her fierce lip-syncing abilities and dramatic performances, but can sometimes be a bit too self-absorbed. She's also a rival of Donna, and the two often compete for the spotlight.

##

Caleb is a character in show type  Movie which is shot in location of Texas. Caleb is A young African American man in his early 20s, Caleb is a talented musician who dreams of making it big in the music industry. He's charismatic, confident, and has a way with words. However, he's also struggling with addiction and is constantly at odds with his strict religious family.

##

Sebastian is a character in show type  Play which is shot in location of Ancient Greece. Sebastian is Viola's twin brother, who is also shipwrecked on the coast of Illyria. Sebastian is rescued by Antonio and becomes embroiled in a series of misunderstandings and mistaken identities. He develops feelings for Lady Olivia, much to the chagrin of Duke Orsino.

##

Will is a character in show type  Movie which is shot in location of Texas. Will is A white man in his early 40s, Will is a successful businessman who's come back to his hometown after many years away. He's confident, charming, and knows how to get what he wants. However, he's also hiding a dark secret from his past that threatens to destroy everything he's worked for.

---

Question: Who is Emily?
Answer:

In [46]:
print(prompt_q2)

Answer the question based on the context below, and if the question cannot be answered based on the context, say "I don't know"

Context:

Alice is a character in show type  Play which is shot in location of England. Alice is A woman in her late 30s, Alice is a warm and nurturing mother of two, including Emily. She's kind-hearted and empathetic, but can be overly protective of her children and prone to worrying. She's married to Jack.

##

Emily is a character in show type  Play which is shot in location of England. Emily is A young woman in her early 20s, Emily is an aspiring actress and Alice's daughter. She has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George.

##

Jack is a character in show type  Play which is shot in location of England. Jack is A middle-aged man in his 40s, Jack is a successful businessman and Sarah's boss. He has a no-nonsense attitude, but is fiercely loyal to his friends and family. He's married to Alice.

##

Sarah is a character in show type  Play which is shot in location of England. Sarah is A woman in her mid-20s, Sarah is a free-spirited artist and Jack's employee. She's creative, unconventional, and passionate about her work. However, she can also be flighty and impulsive at times.

##

George is a character in show type  Play which is shot in location of England. George is A man in his early 30s, George is a charming and charismatic businessman who is in a relationship with Emily. He's ambitious, confident, and always looking for the next big opportunity. However, he's also prone to bending the rules to get what he wants.

##

Lady Olivia is a character in show type  Play which is shot in location of Ancient Greece. Lady Olivia is A wealthy and beautiful noblewoman who has recently become a widow. Lady Olivia is melancholy and withdrawn, and refuses to entertain any suitors. She is the object of Duke Orsino's affections, but is not interested in him. She is also the cousin of Sir Toby Belch and his niece.

##

Jake is a character in show type  Reality Show which is shot in location of USA. Jake is A laid-back and easygoing firefighter, Jake is the quintessential good guy. He's looking for someone who shares his values of honesty and integrity, and who is looking for a stable and committed relationship. He's a bit of a hopeless romantic, and is always looking for ways to sweep his partner off their feet.

##

John is a character in show type  Play which is shot in location of England. John is A man in his 60s, John is a retired professor and Tom's father. He has a dry wit and a love of intellectual debate, but can also be stubborn and set in his ways.

##

Rachel is a character in show type  Play which is shot in location of England. Rachel is A woman in her late 20s, Rachel is a shy and introverted librarian who is in a relationship with Tom. She's intelligent, thoughtful, and has a deep love of books. However, she struggles with social anxiety and often feels like an outsider.

##

Bianca is a character in show type  Play which is shot in location of Ancient Greece. Bianca is Lady Olivia's cunning and quick-witted maid. Bianca is a master of mischief and pranks, and often collaborates with Sir Toby Belch to torment Malvolio. She is also secretly in love with Sir Toby.

##

Abigail is a character in show type  Sitcom which is shot in location of USA. Abigail is A plucky and resourceful young woman who works as a maid in one of the taverns in colonial Williamsburg. Abigail is hard-working and determined, and dreams of one day owning her own business. She has a friendly rivalry with her co-worker, Thomas.

##

Tom is a character in show type  Play which is shot in location of England. Tom is A man in his 50s, Tom is a retired soldier and John's son. He has a no-nonsense approach to life, but is haunted by his experiences in combat and struggles with PTSD. He's also in a relationship with Rachel.

##

Thomas is a character in show type  Sitcom which is shot in location of USA. Thomas is A good-natured and affable young man who also works in the same tavern as Abigail. Thomas is the jester of the group and enjoys making jokes and lightening the mood. He often finds himself caught up in Abigail's schemes.

##

Ava is a character in show type  Limited Series which is shot in location of Australia. Ava is A middle-aged Australian woman in her 50s, Ava is a successful fashion designer who's built an empire on her impeccable taste and attention to detail. She's elegant, sophisticated, and always knows what's in style. She's married to Lucas, but their marriage is strained due to his infidelity. She's also been a mentor to Tahlia, and has helped her navigate the art world.

##

Maria is a character in show type  Movie which is shot in location of Texas. Maria is A middle-aged Latina woman in her 40s, Maria is a hard-working single mother who owns a small family-run diner in a small Texas town. She's fiercely protective of her teenage daughter, Sofia, and is always trying to balance work and family.

##

Tahlia is a character in show type  Limited Series which is shot in location of Australia. Tahlia is A young Indigenous Australian woman in her early 20s, Tahlia is a talented artist who's just been accepted into a prestigious art school. She's the niece of Mia and Max, and they've been like siblings since they were young. She's struggling to find her place in the world as an Indigenous woman, but Mia and Max are always there to support her.

##

Dolly is a character in show type  Musical which is shot in location of USA. Dolly is A bubbly and vivacious performer, Dolly is a fan favorite for her infectious personality and comedic performances. She's known for her campy looks and over-the-top antics, but can struggle with self-doubt and insecurity off stage. She's also a good friend of Johnny, often offering her words of encouragement.

##

Captain James is a character in show type  Sitcom which is shot in location of USA. Captain James is The charismatic and dashing captain of the local militia. Captain James is a ladies' man and enjoys flirting with the women of the town. He has a friendly rivalry with Reverend Brown and often teases him about his piousness.

##

Lucas is a character in show type  Limited Series which is shot in location of Australia. Lucas is A middle-aged Australian man in his 40s, Lucas is a successful businessman and the CEO of a major tech company. He's charming, charismatic, and has a way with people. He's been married to Ava, a successful fashion designer, for many years, but their marriage is on the rocks due to his infidelity.

##

Mrs. Mercer is a character in show type  Sitcom which is shot in location of USA. Mrs. Mercer is The matriarch of the wealthiest family in Williamsburg. Mrs. Mercer is a bit of a snob and enjoys reminding everyone of her social standing. She often hires Abigail to work in her home and is very demanding.

##

Viola is a character in show type  Play which is shot in location of Ancient Greece. Viola is A plucky and resourceful young woman who is shipwrecked on the coast of Illyria. Viola disguises herself as a man, taking on the identity of Cesario, and becomes a servant in Duke Orsino's household. She develops feelings for the Duke, but is unable to reveal her true identity.

##

Mia is a character in show type  Limited Series which is shot in location of Australia. Mia is A young Australian woman in her mid-20s, Mia is a driven and ambitious lawyer who's just landed her dream job at a top law firm in Sydney. She's the younger sister of Max, a former soldier who's struggling with PTSD, and is trying to help him navigate his challenges while also balancing her demanding career.

##

Will is a character in show type  Movie which is shot in location of Texas. Will is A white man in his early 40s, Will is a successful businessman who's come back to his hometown after many years away. He's confident, charming, and knows how to get what he wants. However, he's also hiding a dark secret from his past that threatens to destroy everything he's worked for.

##

Olivia is a character in show type  Reality Show which is shot in location of USA. Olivia is A confident and charismatic marketing executive with a heart of gold. Olivia is always the life of the party, and her infectious personality draws people to her. She's looking for someone who can keep up with her high energy and bring some stability to her life.

##

Malvolio is a character in show type  Play which is shot in location of Ancient Greece. Malvolio is A pompous and self-righteous steward in Lady Olivia's household. Malvolio is humorless and uptight, and is often the target of Sir Toby Belch's pranks. He is secretly in love with Lady Olivia and harbors dreams of marrying her.

##

Sebastian is a character in show type  Play which is shot in location of Ancient Greece. Sebastian is Viola's twin brother, who is also shipwrecked on the coast of Illyria. Sebastian is rescued by Antonio and becomes embroiled in a series of misunderstandings and mistaken identities. He develops feelings for Lady Olivia, much to the chagrin of Duke Orsino.

##

Max is a character in show type  Limited Series which is shot in location of Australia. Max is A white Australian man in his late 20s, Max is a former soldier who's struggling to adjust to civilian life after serving in Afghanistan. He's tough, no-nonsense, and has a strong sense of duty. He's the older brother of Mia, and they've always been close. He's also Ava's godson, and she's always been like a second mother to him.

##

Johnny is a character in show type  Musical which is shot in location of USA. Johnny is A young up-and-coming performer, Johnny is full of energy and enthusiasm. She's known for her edgy and unconventional looks, but can be a bit scatterbrained at times. She looks up to Donna as a mentor and hopes to follow in her footsteps.

##

Feste is a character in show type  Play which is shot in location of Ancient Greece. Feste is A jester and musician who works in Lady Olivia's household. Feste is the wisest character in the play, and uses his wit and intelligence to comment on the actions of the other characters. He is also a confidant to Viola, and helps her navigate her complicated situation.

##

Tyler is a character in show type  Movie which is shot in location of Texas. Tyler is A white man in his mid-30s, Tyler is a tough-as-nails sheriff who takes his job very seriously. He's stoic, no-nonsense, and has a strong sense of justice. However, he's also struggling to come to terms with a recent tragedy in his personal life.

##

Duke Orsino is a character in show type  Play which is shot in location of Ancient Greece. Duke Orsino is A pompous and self-important nobleman who is hopelessly in love with Lady Olivia. Duke Orsino is arrogant and condescending to those around him, but is also a bit of a buffoon. He is related to Sir Toby Belch, who is his uncle.

##

Sonya is a character in show type  Movie which is shot in location of Texas. Sonya is A white woman in her late 20s, Sonya is a free-spirited journalist who's always on the hunt for the next big story. She's passionate, tenacious, and unafraid to speak her mind. However, she's also struggling to balance her career with her personal life, and has a tendency to push people away.

##

Sir Toby Belch is a character in show type  Play which is shot in location of Ancient Greece. Sir Toby Belch is A drunken and lecherous knight who loves nothing more than drinking, carousing, and making mischief. Sir Toby Belch is related to Duke Orsino and Lady Olivia, and uses this connection to his advantage.

##

Karma is a character in show type  Musical which is shot in location of USA. Karma is A chameleon-like performer, Karma is known for her ability to transform herself into any character. She's a master of illusion and is always pushing boundaries with her looks and performances, but can sometimes struggle with authenticity and staying true to herself. She's also a friend of Dolly, often offering her a listening ear when she needs it.

##

Sophia is a character in show type  Reality Show which is shot in location of USA. Sophia is A fun-loving and adventurous travel blogger, Sophia is always looking for her next big adventure. She's looking for someone who can join her on her travels and share in her love of exploration. She's a free spirit who isn't afraid to take risks and try new things.

##

Crystal is a character in show type  Musical which is shot in location of USA. Crystal is A quirky and imaginative performer, Crystal is always surprising audiences with her off-beat performances and unconventional looks. She's known for her unique creativity and imaginative approach, but can sometimes struggle with staying focused and on task. She's also a bit of a wildcard, and the other performers never know what to expect from her.

##

Sir Andrew Aguecheek is a character in show type  Play which is shot in location of Ancient Greece. Sir Andrew Aguecheek is A dim-witted and gullible nobleman who is brought to Illyria by Sir Toby Belch as a potential suitor for Lady Olivia. Sir Andrew Aguecheek is a perennial bachelor and is easily manipulated by those around him.

##

Chloe is a character in show type  Reality Show which is shot in location of USA. Chloe is A driven and ambitious attorney, Chloe is always striving for success. She's looking for someone who can match her intellect and drive, and who is supportive of her career goals. She's a bit guarded when it comes to matters of the heart, but is ready to let her guard down for the right person.

##

Manuel is a character in show type  Movie which is shot in location of Texas. Manuel is A middle-aged Hispanic man in his 50s, Manuel is a proud and hard-working farmer who's struggling to keep his family's farm afloat. He's fiercely loyal to his family and his community, and will do whatever it takes to protect them.

##

Caleb is a character in show type  Movie which is shot in location of Texas. Caleb is A young African American man in his early 20s, Caleb is a talented musician who dreams of making it big in the music industry. He's charismatic, confident, and has a way with words. However, he's also struggling with addiction and is constantly at odds with his strict religious family.

##

Mr. Mercer is a character in show type  Sitcom which is shot in location of USA. Mr. Mercer is The bumbling and absent-minded patriarch of the Mercer family. Mr. Mercer is often clueless about what is going on around him and relies on his wife to keep him in line. He has a secret love of practical jokes and often finds himself in trouble because of them.

##

Maya is a character in show type  Reality Show which is shot in location of USA. Maya is A kind and compassionate nurse with a heart of gold, Maya is always putting others before herself. She's looking for someone who shares her values and is committed to making the world a better place. She's not afraid to speak her mind and stand up for what she believes in.

##

Reverend Brown is a character in show type  Sitcom which is shot in location of USA. Reverend Brown is The pious and stern minister of the local church. Reverend Brown takes his role very seriously and often clashes with the more irreverent characters in the town. He is also secretly in love with Abigail and tries to win her over with his piety.

##

Antonio is a character in show type  Play which is shot in location of Ancient Greece. Antonio is A sea captain who rescues Sebastian from the shipwreck. Antonio becomes devoted to Sebastian and follows him to Illyria, despite the danger it poses to himself.

##

Sable is a character in show type  Musical which is shot in location of USA. Sable is A sultry and dramatic performer, Sable exudes confidence on stage. She's known for her fierce lip-syncing abilities and dramatic performances, but can sometimes be a bit too self-absorbed. She's also a rival of Donna, and the two often compete for the spotlight.

##

Francesca is a character in show type  Opera which is shot in location of Italy. Francesca is A fiery and passionate young woman who works as a blacksmith. She is strong-willed and independent, and her singing voice is bold and powerful. Francesca has caught the eye of Prince Lorenzo, but she is hesitant to give her heart to a man who comes from such a different world.

---

Question: How are Alice, Jack and Emily related?
Answer:

In [47]:
print(prompt_q3)

Answer the question based on the context below, and if the question cannot be answered based on the context, say "I don't know"

Context:

Jack is a character in show type  Play which is shot in location of England. Jack is A middle-aged man in his 40s, Jack is a successful businessman and Sarah's boss. He has a no-nonsense attitude, but is fiercely loyal to his friends and family. He's married to Alice.

##

Sarah is a character in show type  Play which is shot in location of England. Sarah is A woman in her mid-20s, Sarah is a free-spirited artist and Jack's employee. She's creative, unconventional, and passionate about her work. However, she can also be flighty and impulsive at times.

##

Emily is a character in show type  Play which is shot in location of England. Emily is A young woman in her early 20s, Emily is an aspiring actress and Alice's daughter. She has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George.

##

Alice is a character in show type  Play which is shot in location of England. Alice is A woman in her late 30s, Alice is a warm and nurturing mother of two, including Emily. She's kind-hearted and empathetic, but can be overly protective of her children and prone to worrying. She's married to Jack.

##

George is a character in show type  Play which is shot in location of England. George is A man in his early 30s, George is a charming and charismatic businessman who is in a relationship with Emily. He's ambitious, confident, and always looking for the next big opportunity. However, he's also prone to bending the rules to get what he wants.

##

John is a character in show type  Play which is shot in location of England. John is A man in his 60s, John is a retired professor and Tom's father. He has a dry wit and a love of intellectual debate, but can also be stubborn and set in his ways.

##

Tom is a character in show type  Play which is shot in location of England. Tom is A man in his 50s, Tom is a retired soldier and John's son. He has a no-nonsense approach to life, but is haunted by his experiences in combat and struggles with PTSD. He's also in a relationship with Rachel.

##

Rachel is a character in show type  Play which is shot in location of England. Rachel is A woman in her late 20s, Rachel is a shy and introverted librarian who is in a relationship with Tom. She's intelligent, thoughtful, and has a deep love of books. However, she struggles with social anxiety and often feels like an outsider.

##

Sir Toby Belch is a character in show type  Play which is shot in location of Ancient Greece. Sir Toby Belch is A drunken and lecherous knight who loves nothing more than drinking, carousing, and making mischief. Sir Toby Belch is related to Duke Orsino and Lady Olivia, and uses this connection to his advantage.

##

Sir Andrew Aguecheek is a character in show type  Play which is shot in location of Ancient Greece. Sir Andrew Aguecheek is A dim-witted and gullible nobleman who is brought to Illyria by Sir Toby Belch as a potential suitor for Lady Olivia. Sir Andrew Aguecheek is a perennial bachelor and is easily manipulated by those around him.

##

Lady Olivia is a character in show type  Play which is shot in location of Ancient Greece. Lady Olivia is A wealthy and beautiful noblewoman who has recently become a widow. Lady Olivia is melancholy and withdrawn, and refuses to entertain any suitors. She is the object of Duke Orsino's affections, but is not interested in him. She is also the cousin of Sir Toby Belch and his niece.

##

Captain James is a character in show type  Sitcom which is shot in location of USA. Captain James is The charismatic and dashing captain of the local militia. Captain James is a ladies' man and enjoys flirting with the women of the town. He has a friendly rivalry with Reverend Brown and often teases him about his piousness.

##

Malvolio is a character in show type  Play which is shot in location of Ancient Greece. Malvolio is A pompous and self-righteous steward in Lady Olivia's household. Malvolio is humorless and uptight, and is often the target of Sir Toby Belch's pranks. He is secretly in love with Lady Olivia and harbors dreams of marrying her.

##

Duke Orsino is a character in show type  Play which is shot in location of Ancient Greece. Duke Orsino is A pompous and self-important nobleman who is hopelessly in love with Lady Olivia. Duke Orsino is arrogant and condescending to those around him, but is also a bit of a buffoon. He is related to Sir Toby Belch, who is his uncle.

##

Bianca is a character in show type  Play which is shot in location of Ancient Greece. Bianca is Lady Olivia's cunning and quick-witted maid. Bianca is a master of mischief and pranks, and often collaborates with Sir Toby Belch to torment Malvolio. She is also secretly in love with Sir Toby.

##

Viola is a character in show type  Play which is shot in location of Ancient Greece. Viola is A plucky and resourceful young woman who is shipwrecked on the coast of Illyria. Viola disguises herself as a man, taking on the identity of Cesario, and becomes a servant in Duke Orsino's household. She develops feelings for the Duke, but is unable to reveal her true identity.

##

Thomas is a character in show type  Sitcom which is shot in location of USA. Thomas is A good-natured and affable young man who also works in the same tavern as Abigail. Thomas is the jester of the group and enjoys making jokes and lightening the mood. He often finds himself caught up in Abigail's schemes.

##

Feste is a character in show type  Play which is shot in location of Ancient Greece. Feste is A jester and musician who works in Lady Olivia's household. Feste is the wisest character in the play, and uses his wit and intelligence to comment on the actions of the other characters. He is also a confidant to Viola, and helps her navigate her complicated situation.

##

Crystal is a character in show type  Musical which is shot in location of USA. Crystal is A quirky and imaginative performer, Crystal is always surprising audiences with her off-beat performances and unconventional looks. She's known for her unique creativity and imaginative approach, but can sometimes struggle with staying focused and on task. She's also a bit of a wildcard, and the other performers never know what to expect from her.

##

Abigail is a character in show type  Sitcom which is shot in location of USA. Abigail is A plucky and resourceful young woman who works as a maid in one of the taverns in colonial Williamsburg. Abigail is hard-working and determined, and dreams of one day owning her own business. She has a friendly rivalry with her co-worker, Thomas.

##

Dolly is a character in show type  Musical which is shot in location of USA. Dolly is A bubbly and vivacious performer, Dolly is a fan favorite for her infectious personality and comedic performances. She's known for her campy looks and over-the-top antics, but can struggle with self-doubt and insecurity off stage. She's also a good friend of Johnny, often offering her words of encouragement.

##

Karma is a character in show type  Musical which is shot in location of USA. Karma is A chameleon-like performer, Karma is known for her ability to transform herself into any character. She's a master of illusion and is always pushing boundaries with her looks and performances, but can sometimes struggle with authenticity and staying true to herself. She's also a friend of Dolly, often offering her a listening ear when she needs it.

##

Antonio is a character in show type  Play which is shot in location of Ancient Greece. Antonio is A sea captain who rescues Sebastian from the shipwreck. Antonio becomes devoted to Sebastian and follows him to Illyria, despite the danger it poses to himself.

##

Prince Lorenzo is a character in show type  Opera which is shot in location of Italy. Prince Lorenzo is A charming and handsome prince who has recently returned from a long journey abroad. Prince Lorenzo is well-traveled and cultured, and his voice is smooth and velvety. He is searching for true love and has his sights set on a particular young woman.

##

Francesca is a character in show type  Opera which is shot in location of Italy. Francesca is A fiery and passionate young woman who works as a blacksmith. She is strong-willed and independent, and her singing voice is bold and powerful. Francesca has caught the eye of Prince Lorenzo, but she is hesitant to give her heart to a man who comes from such a different world.

##

Maria is a character in show type  Movie which is shot in location of Texas. Maria is A middle-aged Latina woman in her 40s, Maria is a hard-working single mother who owns a small family-run diner in a small Texas town. She's fiercely protective of her teenage daughter, Sofia, and is always trying to balance work and family.

##

Reverend Brown is a character in show type  Sitcom which is shot in location of USA. Reverend Brown is The pious and stern minister of the local church. Reverend Brown takes his role very seriously and often clashes with the more irreverent characters in the town. He is also secretly in love with Abigail and tries to win her over with his piety.

##

Johnny is a character in show type  Musical which is shot in location of USA. Johnny is A young up-and-coming performer, Johnny is full of energy and enthusiasm. She's known for her edgy and unconventional looks, but can be a bit scatterbrained at times. She looks up to Donna as a mentor and hopes to follow in her footsteps.

##

Don Carlo is a character in show type  Opera which is shot in location of Italy. Don Carlo is A charming and charismatic young man who is often the life of the party. Don Carlo is quick-witted and clever, and his singing voice is playful and light. He is friends with Baron Gustavo, but his loyalty is often called into question. He is not above causing mischief and stirring up trouble for his own amusement.

##

Sebastian is a character in show type  Play which is shot in location of Ancient Greece. Sebastian is Viola's twin brother, who is also shipwrecked on the coast of Illyria. Sebastian is rescued by Antonio and becomes embroiled in a series of misunderstandings and mistaken identities. He develops feelings for Lady Olivia, much to the chagrin of Duke Orsino.

##

Chloe is a character in show type  Reality Show which is shot in location of USA. Chloe is A driven and ambitious attorney, Chloe is always striving for success. She's looking for someone who can match her intellect and drive, and who is supportive of her career goals. She's a bit guarded when it comes to matters of the heart, but is ready to let her guard down for the right person.

##

Lucas is a character in show type  Limited Series which is shot in location of Australia. Lucas is A middle-aged Australian man in his 40s, Lucas is a successful businessman and the CEO of a major tech company. He's charming, charismatic, and has a way with people. He's been married to Ava, a successful fashion designer, for many years, but their marriage is on the rocks due to his infidelity.

##

Baron Gustavo is a character in show type  Opera which is shot in location of Italy. Baron Gustavo is A wealthy and arrogant nobleman who loves to flaunt his wealth and status. Baron Gustavo is competitive and ruthless, and his singing voice is powerful and commanding. He is not above using his influence and resources to get what he wants, regardless of who he hurts in the process.

##

Sable is a character in show type  Musical which is shot in location of USA. Sable is A sultry and dramatic performer, Sable exudes confidence on stage. She's known for her fierce lip-syncing abilities and dramatic performances, but can sometimes be a bit too self-absorbed. She's also a rival of Donna, and the two often compete for the spotlight.

##

Sophia is a character in show type  Reality Show which is shot in location of USA. Sophia is A fun-loving and adventurous travel blogger, Sophia is always looking for her next big adventure. She's looking for someone who can join her on her travels and share in her love of exploration. She's a free spirit who isn't afraid to take risks and try new things.

##

Mr. Mercer is a character in show type  Sitcom which is shot in location of USA. Mr. Mercer is The bumbling and absent-minded patriarch of the Mercer family. Mr. Mercer is often clueless about what is going on around him and relies on his wife to keep him in line. He has a secret love of practical jokes and often finds himself in trouble because of them.

##

Mrs. Mercer is a character in show type  Sitcom which is shot in location of USA. Mrs. Mercer is The matriarch of the wealthiest family in Williamsburg. Mrs. Mercer is a bit of a snob and enjoys reminding everyone of her social standing. She often hires Abigail to work in her home and is very demanding.

##

Will is a character in show type  Movie which is shot in location of Texas. Will is A white man in his early 40s, Will is a successful businessman who's come back to his hometown after many years away. He's confident, charming, and knows how to get what he wants. However, he's also hiding a dark secret from his past that threatens to destroy everything he's worked for.

##

Signora Rosa is a character in show type  Opera which is shot in location of Italy. Signora Rosa is A mysterious and alluring woman who runs a local apothecary. Signora Rosa is known for her beauty and her magical remedies, which some believe have mystical powers. Her singing voice is hauntingly beautiful and her demeanor is both captivating and enigmatic.

##

Mia is a character in show type  Limited Series which is shot in location of Australia. Mia is A young Australian woman in her mid-20s, Mia is a driven and ambitious lawyer who's just landed her dream job at a top law firm in Sydney. She's the younger sister of Max, a former soldier who's struggling with PTSD, and is trying to help him navigate his challenges while also balancing her demanding career.

##

Vixen is a character in show type  Musical which is shot in location of USA. Vixen is A fierce and competitive performer, Vixen is always out to win. She's known for her aggressive lip-syncing style and high-energy performances, but can be confrontational and difficult to work with. She's also a rival of Sable, and the two often clash both on and off stage.

##

Marcus is a character in show type  Reality Show which is shot in location of USA. Marcus is A charming and successful entrepreneur, Marcus is used to getting what he wants. He's a smooth talker with a magnetic personality, but can sometimes come across as a bit too self-centered. He's looking for someone who can challenge him and keep him on his toes.

##

James is a character in show type  Reality Show which is shot in location of USA. James is A handsome and athletic personal trainer, James is always up for a challenge. He's looking for someone who is as passionate about fitness as he is, and who can keep up with his intense workout regimen. He can sometimes come across as a bit too competitive, but his heart is always in the right place.

##

Sonya is a character in show type  Movie which is shot in location of Texas. Sonya is A white woman in her late 20s, Sonya is a free-spirited journalist who's always on the hunt for the next big story. She's passionate, tenacious, and unafraid to speak her mind. However, she's also struggling to balance her career with her personal life, and has a tendency to push people away.

##

Ava is a character in show type  Limited Series which is shot in location of Australia. Ava is A middle-aged Australian woman in her 50s, Ava is a successful fashion designer who's built an empire on her impeccable taste and attention to detail. She's elegant, sophisticated, and always knows what's in style. She's married to Lucas, but their marriage is strained due to his infidelity. She's also been a mentor to Tahlia, and has helped her navigate the art world.

##

Max is a character in show type  Limited Series which is shot in location of Australia. Max is A white Australian man in his late 20s, Max is a former soldier who's struggling to adjust to civilian life after serving in Afghanistan. He's tough, no-nonsense, and has a strong sense of duty. He's the older brother of Mia, and they've always been close. He's also Ava's godson, and she's always been like a second mother to him.

---

Question: What are the names of 8 characters in show type Play shot in England?
Answer:

In [48]:
print(basic_prompt_template.format(q1))
print(basic_prompt_template.format(q2))
print(basic_prompt_template.format(q3))

Question: Who is Emily?
Answer:


Question: How are Alice, Jack and Emily related?
Answer:


Question: What are the names of 8 characters in show type Play shot in England?
Answer:

In [49]:
def create_response(prompt):
    model = "gpt-3.5-turbo-instruct"
    response = openai.Completion.create(
        model = model,
        prompt = prompt,
        max_tokens = 400
        )
    return response['choices'][0]['text'].strip()

In [50]:
def gen_basic_rag_response(q, rag_prompt):
    ## Basic prompt response
    basic_prompt = basic_prompt_template.format(q)
    response = create_response(basic_prompt)
    print(f'#### Basic Response is \n {response}')
    rag_response =  create_response(rag_prompt)
    print(f'#### RAG Response is \n {rag_response}')

## Custom Performance Demonstration

TODO: In the cells below, demonstrate the performance of your custom query using at least 2 questions. For each question, show the answer from a basic `Completion` model query as well as the answer from your custom query.

### Question 1

In [51]:
q1

'Who is Emily?'

In [52]:
gen_basic_rag_response(q1, prompt_q1)

#### Basic Response is
 Emily is not a specific person. It can be any person of that name.
#### RAG Response is
 A young woman in her early 20s, aspiring actress, and Alice's daughter who has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George.

### Question 2

In [53]:
q2

'How are Alice, Jack and Emily related?'

In [54]:
gen_basic_rag_response(q2, prompt_q2)

#### Basic Response is
 There is not enough information provided to determine their exact relationship. They could be siblings, friends, cousins, or even strangers.
#### RAG Response is
 Alice is Emily's mother, Jack is Emily's father, and they are married.

### Question 3

In [55]:
q3

'What are the names of 8 characters in show type Play shot in England?'

In [56]:
gen_basic_rag_response(q3, prompt_q3)

#### Basic Response is
 1. Romeo
2. Juliet
3. Hamlet
4. Ophelia
5. Macbeth
6. Lady Macbeth
7. King Lear
8. Miranda
#### RAG Response is
 Jack, Sarah, Emily, Alice, George, John, Tom, Rachel