This is a starter notebook for the project, you'll have to import the libraries you'll need, you can find a list of the ones available in this workspace in the requirements.txt file in this workspace.

In [1]:
!pip install pandas
#restart kernel after installing pandas and continue from next cell

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 54.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.7)
Collecting tzdata>=2022.7
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 2.4 MB/s eta 0:00:0000:01
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.2.2 tzdata-2024.1

In [1]:
#from langchain.llms import OpenAI
import openai
import pandas as pd
import numpy as np

In [37]:
openai.api_key = "YOUR_API_KEY"

Generate real estate listings using a Large Language Model. Generate at least 10 listings This can involve creating prompts for the LLM to produce descriptions of various properties

##### Create 15 real estate listings and store it in pandas dataframe

In [4]:
prompt = """
Generate 15 unique, diverse and realistic real estate listings. Listing should contain the
following fields. Description should describe the real estate property in 
pleasant manner. Limit the length of Description to 50 words. Neighborhood Description should describe neighborhood 
in a pleasant manner. It should not exceed 100 words.Number of Bedrooms
and Bathrooms should be integer.Number of bathrooms should be less than
number of bedrooms. Please do not display output number order.

Neighborhood, Price, Bedrooms, Bathrooms, House Size, Description, Neighborhood Description
"""

In [5]:
model = "gpt-3.5-turbo-instruct"
response = openai.Completion.create(
    model = model,
    prompt = prompt,
    max_tokens = 3500
        )
response['choices'][0]['text'].strip()

"1. Neighborhood: Historic Downtown\nPrice: $895,000\nBedrooms: 3\nBathrooms: 2\nHouse Size: 1,800 sqft\nDescription: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.\nNeighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.\n\n2. Neighborhood: Waterfront\nPrice: $1,250,000\nBedrooms: 2\nBathrooms: 2\nHouse Size: 2,200 sqft\nDescription: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.\nNeighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area.\n\n3. Neighborhood: Suburban Heights\nPrice: $550,000\nBedrooms: 4\nBathrooms: 2\nHouse Size: 2,500 sqft\nDescription: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.\nNeighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.\n\n4. Neighborhood: Beachfront\nPrice: $3,500,000\nBedrooms: 5\nBathrooms: 4\nHouse Size: 4,000 sqft\nDescription: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.\nNeighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise.\n\n5. Neighborhood: Mountain View\nPrice: $750,000\nBedrooms: 3\nBathrooms: 2\nHouse Size: 2,000 sqft\nDescription: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.\nNeighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.\n\n6. Neighborhood: Urban Downtown\nPrice: $1,100,000\nBedrooms: 2\nBathrooms: 2\nHouse Size: 1,500 sqft\nDescription: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.\nNeighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.\n\n7. Neighborhood: Lakeside Retreat\nPrice: $600,000\nBedrooms: 4\nBathrooms: 3\nHouse Size: 2,500 sqft\nDescription: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.\nNeighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise.\n\n8. Neighborhood: Historic District\nPrice: $1,500,000\nBedrooms: 6\nBathrooms: 4\nHouse Size: 3,500 sqft\nDescription: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.\nNeighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.\n\n9. Neighborhood: Golf Course Community\nPrice: $900,000\nBedrooms: 5\nBathrooms: 4\nHouse Size: 4,000 sqft\nDescription: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.\nNeighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.\n\n10. Neighborhood: Arts District\nPrice: $800,000\nBedrooms: 3\nBathrooms: 2\nHouse Size: 1,800 sqft\nDescription: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.\nNeighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.\n\n11. Neighborhood: Country Living\nPrice: $450,000\nBedrooms: 4\nBathrooms: 3\nHouse Size: 2,000 sqft\nDescription: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.\nNeighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.\n\n12. Neighborhood: Riverfront\nPrice: $1,800,000\nBedrooms: 6\nBathrooms: 4\nHouse Size: 4,500 sqft\nDescription: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.\nNeighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.\n\n13. Neighborhood: Family-Friendly Subdivision\nPrice: $650,000\nBedrooms: 4\nBathrooms: 3\nHouse Size: 3,000 sqft\nDescription: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.\nNeighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.\n\n14. Neighborhood: Oceanview\nPrice: $2,200,000\nBedrooms: 3\nBathrooms: 2\nHouse Size: 2,500 sqft\nDescription: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.\nNeighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area.\n\n15. Neighborhood: Gated Community\nPrice: $2,500,000\nBedrooms: 5\nBathrooms: 4\nHouse Size: 5,000 sqft\nDescription: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.\nNeighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood."

In [7]:
output = response['choices'][0]['text'].strip()

In [9]:
print(output)

1. Neighborhood: Historic Downtown
Price: $895,000
Bedrooms: 3
Bathrooms: 2
House Size: 1,800 sqft
Description: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.
Neighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.

2. Neighborhood: Waterfront
Price: $1,250,000
Bedrooms: 2
Bathrooms: 2
House Size: 2,200 sqft
Description: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.
Neighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area.

3. Neighborhood: Suburban Heights
Price: $550,000
Bedrooms: 4
Bathrooms: 2
House Size: 2,500 sqft
Description: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.
Neighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.

4. Neighborhood: Beachfront
Price: $3,500,000
Bedrooms: 5
Bathrooms: 4
House Size: 4,000 sqft
Description: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.
Neighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise.

5. Neighborhood: Mountain View
Price: $750,000
Bedrooms: 3
Bathrooms: 2
House Size: 2,000 sqft
Description: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.
Neighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.

6. Neighborhood: Urban Downtown
Price: $1,100,000
Bedrooms: 2
Bathrooms: 2
House Size: 1,500 sqft
Description: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.
Neighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.

7. Neighborhood: Lakeside Retreat
Price: $600,000
Bedrooms: 4
Bathrooms: 3
House Size: 2,500 sqft
Description: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.
Neighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise.

8. Neighborhood: Historic District
Price: $1,500,000
Bedrooms: 6
Bathrooms: 4
House Size: 3,500 sqft
Description: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.
Neighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.

9. Neighborhood: Golf Course Community
Price: $900,000
Bedrooms: 5
Bathrooms: 4
House Size: 4,000 sqft
Description: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.
Neighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.

10. Neighborhood: Arts District
Price: $800,000
Bedrooms: 3
Bathrooms: 2
House Size: 1,800 sqft
Description: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.
Neighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.

11. Neighborhood: Country Living
Price: $450,000
Bedrooms: 4
Bathrooms: 3
House Size: 2,000 sqft
Description: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.
Neighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.

12. Neighborhood: Riverfront
Price: $1,800,000
Bedrooms: 6
Bathrooms: 4
House Size: 4,500 sqft
Description: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.
Neighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.

13. Neighborhood: Family-Friendly Subdivision
Price: $650,000
Bedrooms: 4
Bathrooms: 3
House Size: 3,000 sqft
Description: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.
Neighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.

14. Neighborhood: Oceanview
Price: $2,200,000
Bedrooms: 3
Bathrooms: 2
House Size: 2,500 sqft
Description: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.
Neighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area.

15. Neighborhood: Gated Community
Price: $2,500,000
Bedrooms: 5
Bathrooms: 4
House Size: 5,000 sqft
Description: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.
Neighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.

In [10]:
out = output.split("\n")

In [11]:
out

['1. Neighborhood: Historic Downtown',
 'Price: $895,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 1,800 sqft',
 'Description: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.',
 'Neighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.',
 '',
 '2. Neighborhood: Waterfront',
 'Price: $1,250,000',
 'Bedrooms: 2',
 'Bathrooms: 2',
 'House Size: 2,200 sqft',
 'Description: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.',
 "Neighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area.",
 '',
 '3. Neighborhood: Suburban Heights',
 'Price: $550,000',
 'Bedrooms: 4',
 'Bathrooms: 2',
 'House Size: 2,500 sqft',
 'Description: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.',
 'Neighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.',
 '',
 '4. Neighborhood: Beachfront',
 'Price: $3,500,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 4,000 sqft',
 'Description: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.',
 "Neighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise.",
 '',
 '5. Neighborhood: Mountain View',
 'Price: $750,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 2,000 sqft',
 'Description: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.',
 'Neighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.',
 '',
 '6. Neighborhood: Urban Downtown',
 'Price: $1,100,000',
 'Bedrooms: 2',
 'Bathrooms: 2',
 'House Size: 1,500 sqft',
 'Description: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.',
 'Neighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.',
 '',
 '7. Neighborhood: Lakeside Retreat',
 'Price: $600,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 2,500 sqft',
 'Description: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.',
 "Neighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise.",
 '',
 '8. Neighborhood: Historic District',
 'Price: $1,500,000',
 'Bedrooms: 6',
 'Bathrooms: 4',
 'House Size: 3,500 sqft',
 'Description: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.',
 'Neighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.',
 '',
 '9. Neighborhood: Golf Course Community',
 'Price: $900,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 4,000 sqft',
 'Description: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.',
 'Neighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.',
 '',
 '10. Neighborhood: Arts District',
 'Price: $800,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 1,800 sqft',
 "Description: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.",
 'Neighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.',
 '',
 '11. Neighborhood: Country Living',
 'Price: $450,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 2,000 sqft',
 'Description: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.',
 'Neighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.',
 '',
 '12. Neighborhood: Riverfront',
 'Price: $1,800,000',
 'Bedrooms: 6',
 'Bathrooms: 4',
 'House Size: 4,500 sqft',
 'Description: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.',
 'Neighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.',
 '',
 '13. Neighborhood: Family-Friendly Subdivision',
 'Price: $650,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 3,000 sqft',
 'Description: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.',
 'Neighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.',
 '',
 '14. Neighborhood: Oceanview',
 'Price: $2,200,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 2,500 sqft',
 'Description: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.',
 "Neighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area.",
 '',
 '15. Neighborhood: Gated Community',
 'Price: $2,500,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 5,000 sqft',
 'Description: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.',
 'Neighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.']

In [12]:
len(out)

119

In [13]:
ll = []
for i in out:
    if i=='':
        continue
    else:
        ll.append(i)

In [14]:
len(ll)

105

In [15]:
ll

['1. Neighborhood: Historic Downtown',
 'Price: $895,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 1,800 sqft',
 'Description: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.',
 'Neighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.',
 '2. Neighborhood: Waterfront',
 'Price: $1,250,000',
 'Bedrooms: 2',
 'Bathrooms: 2',
 'House Size: 2,200 sqft',
 'Description: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.',
 "Neighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area.",
 '3. Neighborhood: Suburban Heights',
 'Price: $550,000',
 'Bedrooms: 4',
 'Bathrooms: 2',
 'House Size: 2,500 sqft',
 'Description: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.',
 'Neighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.',
 '4. Neighborhood: Beachfront',
 'Price: $3,500,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 4,000 sqft',
 'Description: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.',
 "Neighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise.",
 '5. Neighborhood: Mountain View',
 'Price: $750,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 2,000 sqft',
 'Description: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.',
 'Neighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.',
 '6. Neighborhood: Urban Downtown',
 'Price: $1,100,000',
 'Bedrooms: 2',
 'Bathrooms: 2',
 'House Size: 1,500 sqft',
 'Description: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.',
 'Neighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.',
 '7. Neighborhood: Lakeside Retreat',
 'Price: $600,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 2,500 sqft',
 'Description: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.',
 "Neighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise.",
 '8. Neighborhood: Historic District',
 'Price: $1,500,000',
 'Bedrooms: 6',
 'Bathrooms: 4',
 'House Size: 3,500 sqft',
 'Description: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.',
 'Neighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.',
 '9. Neighborhood: Golf Course Community',
 'Price: $900,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 4,000 sqft',
 'Description: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.',
 'Neighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.',
 '10. Neighborhood: Arts District',
 'Price: $800,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 1,800 sqft',
 "Description: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.",
 'Neighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.',
 '11. Neighborhood: Country Living',
 'Price: $450,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 2,000 sqft',
 'Description: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.',
 'Neighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.',
 '12. Neighborhood: Riverfront',
 'Price: $1,800,000',
 'Bedrooms: 6',
 'Bathrooms: 4',
 'House Size: 4,500 sqft',
 'Description: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.',
 'Neighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.',
 '13. Neighborhood: Family-Friendly Subdivision',
 'Price: $650,000',
 'Bedrooms: 4',
 'Bathrooms: 3',
 'House Size: 3,000 sqft',
 'Description: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.',
 'Neighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.',
 '14. Neighborhood: Oceanview',
 'Price: $2,200,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 2,500 sqft',
 'Description: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.',
 "Neighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area.",
 '15. Neighborhood: Gated Community',
 'Price: $2,500,000',
 'Bedrooms: 5',
 'Bathrooms: 4',
 'House Size: 5,000 sqft',
 'Description: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.',
 'Neighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.']

In [58]:
len(ll)

105

In [16]:
property_data = ll.copy()

In [25]:
properties = []

for i in range(0, len(property_data), 7):
    property_info = property_data[i:i+7]
    print(property_info)
    properties.append(property_info)

['1. Neighborhood: Historic Downtown', 'Price: $895,000', 'Bedrooms: 3', 'Bathrooms: 2', 'House Size: 1,800 sqft', 'Description: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.', 'Neighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.']
['2. Neighborhood: Waterfront', 'Price: $1,250,000', 'Bedrooms: 2', 'Bathrooms: 2', 'House Size: 2,200 sqft', 'Description: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.', "Neighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area."]
['3. Neighborhood: Suburban Heights', 'Price: $550,000', 'Bedrooms: 4', 'Bathrooms: 2', 'House Size: 2,500 sqft', 'Description: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.', 'Neighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.']
['4. Neighborhood: Beachfront', 'Price: $3,500,000', 'Bedrooms: 5', 'Bathrooms: 4', 'House Size: 4,000 sqft', 'Description: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.', "Neighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise."]
['5. Neighborhood: Mountain View', 'Price: $750,000', 'Bedrooms: 3', 'Bathrooms: 2', 'House Size: 2,000 sqft', 'Description: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.', 'Neighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.']
['6. Neighborhood: Urban Downtown', 'Price: $1,100,000', 'Bedrooms: 2', 'Bathrooms: 2', 'House Size: 1,500 sqft', 'Description: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.', 'Neighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.']
['7. Neighborhood: Lakeside Retreat', 'Price: $600,000', 'Bedrooms: 4', 'Bathrooms: 3', 'House Size: 2,500 sqft', 'Description: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.', "Neighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise."]
['8. Neighborhood: Historic District', 'Price: $1,500,000', 'Bedrooms: 6', 'Bathrooms: 4', 'House Size: 3,500 sqft', 'Description: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.', 'Neighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.']
['9. Neighborhood: Golf Course Community', 'Price: $900,000', 'Bedrooms: 5', 'Bathrooms: 4', 'House Size: 4,000 sqft', 'Description: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.', 'Neighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.']
['10. Neighborhood: Arts District', 'Price: $800,000', 'Bedrooms: 3', 'Bathrooms: 2', 'House Size: 1,800 sqft', "Description: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.", 'Neighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.']
['11. Neighborhood: Country Living', 'Price: $450,000', 'Bedrooms: 4', 'Bathrooms: 3', 'House Size: 2,000 sqft', 'Description: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.', 'Neighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.']
['12. Neighborhood: Riverfront', 'Price: $1,800,000', 'Bedrooms: 6', 'Bathrooms: 4', 'House Size: 4,500 sqft', 'Description: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.', 'Neighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.']
['13. Neighborhood: Family-Friendly Subdivision', 'Price: $650,000', 'Bedrooms: 4', 'Bathrooms: 3', 'House Size: 3,000 sqft', 'Description: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.', 'Neighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.']
['14. Neighborhood: Oceanview', 'Price: $2,200,000', 'Bedrooms: 3', 'Bathrooms: 2', 'House Size: 2,500 sqft', 'Description: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.', "Neighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area."]
['15. Neighborhood: Gated Community', 'Price: $2,500,000', 'Bedrooms: 5', 'Bathrooms: 4', 'House Size: 5,000 sqft', 'Description: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.', 'Neighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.']

In [26]:
len(properties)

15

In [27]:
properties[0]

['1. Neighborhood: Historic Downtown',
 'Price: $895,000',
 'Bedrooms: 3',
 'Bathrooms: 2',
 'House Size: 1,800 sqft',
 'Description: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.',
 'Neighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.']

In [42]:
import pandas as pd

In [51]:
prop_d = {}
df = pd.DataFrame()
for ind_j in range(len(properties)):
    prop_d = {}
    for ind, i in enumerate(properties[ind_j]):
        if ind==0:
            val = i.split(":")[1]
            key = i.split(":")[0].split(".")[1]
        else:
            val = i.split(":")[1]
            key = i.split(":")[0]
        prop_d[key] = val
    df_1 = pd.DataFrame(prop_d, index=range(0,1)) #, ignore_index=True)
    df = pd.concat([df,df_1], axis=0)

df

,Neighborhood,Price,Bedrooms,Bathrooms,House Size,Description,Neighborhood Description
0,Historic Downtown,"$895,000",3,2,"1,800 sqft",Charming Victorian home located in the heart ...,Immerse yourself in the quaint and vibrant at...
0,Waterfront,"$1,250,000",2,2,"2,200 sqft",Stunning waterfront property with panoramic v...,Experience the ultimate waterfront lifestyle ...
0,Suburban Heights,"$550,000",4,2,"2,500 sqft","Welcome home to this spacious 4 bedroom, 2 ba...",Escape the hustle and bustle of the city and ...
0,Beachfront,"$3,500,000",5,4,"4,000 sqft",Luxurious beachfront estate with stunning oce...,Unwind and soak up the sun in this prestigiou...
0,Mountain View,"$750,000",3,2,"2,000 sqft",Nestled among the tranquil mountain landscape...,Surround yourself with nature in the serene a...
0,Urban Downtown,"$1,100,000",2,2,"1,500 sqft",Live in the heart of the city in this modern ...,Be in the center of it all in bustling Urban ...
0,Lakeside Retreat,"$600,000",4,3,"2,500 sqft",Escape to your own lakeside oasis in this bea...,Experience the tranquility of lakeside living...
0,Historic District,"$1,500,000",6,4,"3,500 sqft",Immerse yourself in the rich history of this ...,Step back in time and stroll through the char...
0,Golf Course Community,"$900,000",5,4,"4,000 sqft",Live the resort lifestyle in this spacious an...,Tee off in style and experience the luxurious...
0,Arts District,"$800,000",3,2,"1,800 sqft","This modern and sleek 3 bedroom, 2 bathroom l...",Immerse yourself in the creative and bustling...
0,Country Living,"$450,000",4,3,"2,000 sqft",Enjoy the peace and quiet of country living i...,Get away from the noise and chaos of the city...
0,Riverfront,"$1,800,000",6,4,"4,500 sqft",Treat yourself to luxury living in this elega...,Experience the ultimate waterfront lifestyle ...
0,Family-Friendly Subdivision,"$650,000",4,3,"3,000 sqft",Make memories with your family in this spacio...,Discover the perfect place to raise a family ...
0,Oceanview,"$2,200,000",3,2,"2,500 sqft",Wake up to breathtaking ocean views in this s...,Indulge in the coastal lifestyle in the elite...
0,Gated Community,"$2,500,000",5,4,"5,000 sqft",Live in luxury and privacy in this exquisite ...,Experience the ultimate in exclusivity and se...

In [52]:
df.reset_index(inplace=True, drop='first')
df

,Neighborhood,Price,Bedrooms,Bathrooms,House Size,Description,Neighborhood Description
0,Historic Downtown,"$895,000",3,2,"1,800 sqft",Charming Victorian home located in the heart ...,Immerse yourself in the quaint and vibrant at...
1,Waterfront,"$1,250,000",2,2,"2,200 sqft",Stunning waterfront property with panoramic v...,Experience the ultimate waterfront lifestyle ...
2,Suburban Heights,"$550,000",4,2,"2,500 sqft","Welcome home to this spacious 4 bedroom, 2 ba...",Escape the hustle and bustle of the city and ...
3,Beachfront,"$3,500,000",5,4,"4,000 sqft",Luxurious beachfront estate with stunning oce...,Unwind and soak up the sun in this prestigiou...
4,Mountain View,"$750,000",3,2,"2,000 sqft",Nestled among the tranquil mountain landscape...,Surround yourself with nature in the serene a...
5,Urban Downtown,"$1,100,000",2,2,"1,500 sqft",Live in the heart of the city in this modern ...,Be in the center of it all in bustling Urban ...
6,Lakeside Retreat,"$600,000",4,3,"2,500 sqft",Escape to your own lakeside oasis in this bea...,Experience the tranquility of lakeside living...
7,Historic District,"$1,500,000",6,4,"3,500 sqft",Immerse yourself in the rich history of this ...,Step back in time and stroll through the char...
8,Golf Course Community,"$900,000",5,4,"4,000 sqft",Live the resort lifestyle in this spacious an...,Tee off in style and experience the luxurious...
9,Arts District,"$800,000",3,2,"1,800 sqft","This modern and sleek 3 bedroom, 2 bathroom l...",Immerse yourself in the creative and bustling...
10,Country Living,"$450,000",4,3,"2,000 sqft",Enjoy the peace and quiet of country living i...,Get away from the noise and chaos of the city...
11,Riverfront,"$1,800,000",6,4,"4,500 sqft",Treat yourself to luxury living in this elega...,Experience the ultimate waterfront lifestyle ...
12,Family-Friendly Subdivision,"$650,000",4,3,"3,000 sqft",Make memories with your family in this spacio...,Discover the perfect place to raise a family ...
13,Oceanview,"$2,200,000",3,2,"2,500 sqft",Wake up to breathtaking ocean views in this s...,Indulge in the coastal lifestyle in the elite...
14,Gated Community,"$2,500,000",5,4,"5,000 sqft",Live in luxury and privacy in this exquisite ...,Experience the ultimate in exclusivity and se...

In [53]:
df.to_csv('./listings.csv')
!ls -ltr ./

## Save contents of generated listings to disk

total 136
-rw-r--r-- 1 student student    159 May 20 18:04 HomeMatch.py
-rw-r--r-- 1 student student    196 May 20 18:06 requirements.txt
-rw-r--r-- 1 student student 118440 May 25 04:34 HomeMatch.ipynb
-rw-r--r-- 1 student student   9965 May 25 04:35 listings.csv

In [54]:
df.columns

Index([' Neighborhood', 'Price', 'Bedrooms', 'Bathrooms', 'House Size',
       'Description', 'Neighborhood Description'],
      dtype='object')

In [59]:
df['basic_desc'] = df.apply(lambda x: {'Neighborhood': x[' Neighborhood'], 'Price': x['Price'], 'Bedrooms': x['Bedrooms'], 'Bathrooms': x['Bathrooms'], 'House Size': x['House Size']}, axis=1)

In [61]:
df['basic_desc']

0     {'Neighborhood': ' Historic Downtown', 'Price'...
1     {'Neighborhood': ' Waterfront', 'Price': ' $1,...
2     {'Neighborhood': ' Suburban Heights', 'Price':...
3     {'Neighborhood': ' Beachfront', 'Price': ' $3,...
4     {'Neighborhood': ' Mountain View', 'Price': ' ...
5     {'Neighborhood': ' Urban Downtown', 'Price': '...
6     {'Neighborhood': ' Lakeside Retreat', 'Price':...
7     {'Neighborhood': ' Historic District', 'Price'...
8     {'Neighborhood': ' Golf Course Community', 'Pr...
9     {'Neighborhood': ' Arts District', 'Price': ' ...
10    {'Neighborhood': ' Country Living', 'Price': '...
11    {'Neighborhood': ' Riverfront', 'Price': ' $1,...
12    {'Neighborhood': ' Family-Friendly Subdivision...
13    {'Neighborhood': ' Oceanview', 'Price': ' $2,2...
14    {'Neighborhood': ' Gated Community', 'Price': ...
Name: basic_desc, dtype: object

In [81]:
df['Basic Description'] = df.apply(lambda x: f'This house exists in the neighborhood of {x[" Neighborhood"]} with total size of {x["House Size"]}. Number of bedrooms and bathrooms in the house is {x["Bedrooms"]} and {x["Bathrooms"]} respectively. Price of the house is {x["Price"]}', axis=1)

In [82]:
df['Basic Description'][0]

'This house exists in the neighborhood of  Historic Downtown with total size of  1,800 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is  $895,000'

In [83]:
df[['Basic Description', 'Description', 'Neighborhood Description']]

,Basic Description,Description,Neighborhood Description
0,This house exists in the neighborhood of Hist...,Charming Victorian home located in the heart ...,Immerse yourself in the quaint and vibrant at...
1,This house exists in the neighborhood of Wate...,Stunning waterfront property with panoramic v...,Experience the ultimate waterfront lifestyle ...
2,This house exists in the neighborhood of Subu...,"Welcome home to this spacious 4 bedroom, 2 ba...",Escape the hustle and bustle of the city and ...
3,This house exists in the neighborhood of Beac...,Luxurious beachfront estate with stunning oce...,Unwind and soak up the sun in this prestigiou...
4,This house exists in the neighborhood of Moun...,Nestled among the tranquil mountain landscape...,Surround yourself with nature in the serene a...
5,This house exists in the neighborhood of Urba...,Live in the heart of the city in this modern ...,Be in the center of it all in bustling Urban ...
6,This house exists in the neighborhood of Lake...,Escape to your own lakeside oasis in this bea...,Experience the tranquility of lakeside living...
7,This house exists in the neighborhood of Hist...,Immerse yourself in the rich history of this ...,Step back in time and stroll through the char...
8,This house exists in the neighborhood of Golf...,Live the resort lifestyle in this spacious an...,Tee off in style and experience the luxurious...
9,This house exists in the neighborhood of Arts...,"This modern and sleek 3 bedroom, 2 bathroom l...",Immerse yourself in the creative and bustling...
10,This house exists in the neighborhood of Coun...,Enjoy the peace and quiet of country living i...,Get away from the noise and chaos of the city...
11,This house exists in the neighborhood of Rive...,Treat yourself to luxury living in this elega...,Experience the ultimate waterfront lifestyle ...
12,This house exists in the neighborhood of Fami...,Make memories with your family in this spacio...,Discover the perfect place to raise a family ...
13,This house exists in the neighborhood of Ocea...,Wake up to breathtaking ocean views in this s...,Indulge in the coastal lifestyle in the elite...
14,This house exists in the neighborhood of Gate...,Live in luxury and privacy in this exquisite ...,Experience the ultimate in exclusivity and se...

In [84]:
df[['Basic Description', 'Description', 'Neighborhood Description']].to_csv('./listings_1.csv', index=False )
# We are going to use this csv file going forward
# The file consists of Basic Description, Description and Neighborhood description

In [85]:
!ls -ltr ./

total 188
-rw-r--r-- 1 student student    159 May 20 18:04 HomeMatch.py
-rw-r--r-- 1 student student    196 May 20 18:06 requirements.txt
-rw-r--r-- 1 student student   9965 May 25 04:35 listings.csv
-rw-r--r-- 1 student student 156355 May 25 05:10 HomeMatch.ipynb
-rw-r--r-- 1 student student  12117 May 25 05:12 listings_1.csv

In [86]:
df_t = pd.read_csv('./listings_1.csv')
df_t

,Basic Description,Description,Neighborhood Description
0,This house exists in the neighborhood of Hist...,Charming Victorian home located in the heart ...,Immerse yourself in the quaint and vibrant at...
1,This house exists in the neighborhood of Wate...,Stunning waterfront property with panoramic v...,Experience the ultimate waterfront lifestyle ...
2,This house exists in the neighborhood of Subu...,"Welcome home to this spacious 4 bedroom, 2 ba...",Escape the hustle and bustle of the city and ...
3,This house exists in the neighborhood of Beac...,Luxurious beachfront estate with stunning oce...,Unwind and soak up the sun in this prestigiou...
4,This house exists in the neighborhood of Moun...,Nestled among the tranquil mountain landscape...,Surround yourself with nature in the serene a...
5,This house exists in the neighborhood of Urba...,Live in the heart of the city in this modern ...,Be in the center of it all in bustling Urban ...
6,This house exists in the neighborhood of Lake...,Escape to your own lakeside oasis in this bea...,Experience the tranquility of lakeside living...
7,This house exists in the neighborhood of Hist...,Immerse yourself in the rich history of this ...,Step back in time and stroll through the char...
8,This house exists in the neighborhood of Golf...,Live the resort lifestyle in this spacious an...,Tee off in style and experience the luxurious...
9,This house exists in the neighborhood of Arts...,"This modern and sleek 3 bedroom, 2 bathroom l...",Immerse yourself in the creative and bustling...
10,This house exists in the neighborhood of Coun...,Enjoy the peace and quiet of country living i...,Get away from the noise and chaos of the city...
11,This house exists in the neighborhood of Rive...,Treat yourself to luxury living in this elega...,Experience the ultimate waterfront lifestyle ...
12,This house exists in the neighborhood of Fami...,Make memories with your family in this spacio...,Discover the perfect place to raise a family ...
13,This house exists in the neighborhood of Ocea...,Wake up to breathtaking ocean views in this s...,Indulge in the coastal lifestyle in the elite...
14,This house exists in the neighborhood of Gate...,Live in luxury and privacy in this exquisite ...,Experience the ultimate in exclusivity and se...

### Load the information from csv file, create embeddings and store it in vector database

In [2]:
# let us load all langchain, openai and other stuff
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from langchain import LLMChain
from langchain.chains.question_answering import load_qa_chain

In [3]:
loader = CSVLoader(file_path='./listings_1.csv')
docs = loader.load()
docs

[Document(page_content='Basic Description: This house exists in the neighborhood of  Historic Downtown with total size of  1,800 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is  $895,000\nDescription: Charming Victorian home located in the heart of Historic Downtown. This cozy and spacious 3 bedroom, 2 bathroom residence boasts elegant hardwood floors, a bright and airy kitchen, and a private backyard perfect for entertaining. Enjoy the best of downtown living with shops, restaurants, and parks just steps away.\nNeighborhood Description: Immerse yourself in the quaint and vibrant atmosphere of Historic Downtown. With beautifully preserved landmarks, lively entertainment options, and a strong sense of community, this charming neighborhood is the perfect blend of old-world elegance and modern convenience.', metadata={'source': './listings_1.csv', 'row': 0}),
 Document(page_content="Basic Description: This house exists in the neighborhood of  Waterfront with total size of  2,200 sqft. Number of bedrooms and bathrooms in the house is  2 and  2 respectively. Price of the house is  $1,250,000\nDescription: Stunning waterfront property with panoramic views of the bay. This 2 bedroom, 2 bathroom home offers a spacious and open floor plan, modern finishes, and a private boat dock. Relax on your balcony and watch the sunset over the glistening water, or take a short walk to the nearby marina and restaurants.\nNeighborhood Description: Experience the ultimate waterfront lifestyle in this desirable neighborhood. With easy access to boating, fishing, and dining options, you'll never run out of ways to enjoy the stunning bay views. Come see why Waterfront is one of the most sought-after communities in the area.", metadata={'source': './listings_1.csv', 'row': 1}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Suburban Heights with total size of  2,500 sqft. Number of bedrooms and bathrooms in the house is  4 and  2 respectively. Price of the house is  $550,000\nDescription: Welcome home to this spacious 4 bedroom, 2 bathroom retreat in the peaceful Suburban Heights neighborhood. Featuring a large backyard, perfect for family gatherings, and a cozy fireplace for those chilly evenings. This well-maintained home is located just minutes away from top-rated schools and shopping.\nNeighborhood Description: Escape the hustle and bustle of the city and find tranquility in Suburban Heights. This family-friendly neighborhood offers a safe and welcoming environment, with tree-lined streets, local parks, and a strong sense of community. Enjoy a peaceful suburban lifestyle without sacrificing convenience.', metadata={'source': './listings_1.csv', 'row': 2}),
 Document(page_content="Basic Description: This house exists in the neighborhood of  Beachfront with total size of  4,000 sqft. Number of bedrooms and bathrooms in the house is  5 and  4 respectively. Price of the house is  $3,500,000\nDescription: Luxurious beachfront estate with stunning ocean views. This 5 bedroom, 4 bathroom home offers top-of-the-line finishes, a gourmet kitchen, and a private pool and spa. Take a short stroll down to the beach and enjoy the sun, sand, and surf. This is coastal living at its finest.\nNeighborhood Description: Unwind and soak up the sun in this prestigious beachfront community. With breathtaking ocean views, white sandy beaches, and exclusive amenities, Beachfront is the epitome of luxury coastal living. Don't miss your chance to own a piece of paradise.", metadata={'source': './listings_1.csv', 'row': 3}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Mountain View with total size of  2,000 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is  $750,000\nDescription: Nestled among the tranquil mountain landscape, this 3 bedroom, 2 bathroom home offers a serene retreat from city life. Enjoy spectacular views from every room, a spacious deck for outdoor entertaining, and a cozy fireplace for those chilly nights. Just minutes away from hiking trails and outdoor activities.\nNeighborhood Description: Surround yourself with nature in the serene and picturesque neighborhood of Mountain View. With breathtaking mountain views and easy access to outdoor activities, this community is perfect for those who love the great outdoors. Escape the chaos of city living and find peace in Mountain View.', metadata={'source': './listings_1.csv', 'row': 4}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Urban Downtown with total size of  1,500 sqft. Number of bedrooms and bathrooms in the house is  2 and  2 respectively. Price of the house is  $1,100,000\nDescription: Live in the heart of the city in this modern and stylish 2 bedroom, 2 bathroom condo in Urban Downtown. With high-end finishes, an open floor plan, and access to a rooftop pool and fitness center, this is urban living at its finest. Just steps away from trendy restaurants, shops, and nightlife.\nNeighborhood Description: Be in the center of it all in bustling Urban Downtown. This lively and vibrant neighborhood offers a bustling city atmosphere with an array of dining, shopping, and entertainment options. Enjoy the convenience and excitement of city living in this popular urban community.', metadata={'source': './listings_1.csv', 'row': 5}),
 Document(page_content="Basic Description: This house exists in the neighborhood of  Lakeside Retreat with total size of  2,500 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $600,000\nDescription: Escape to your own lakeside oasis in this beautifully appointed 4 bedroom, 3 bathroom home. With stunning lake views, a private dock, and a spacious deck for entertaining, this home is perfect for relaxation and entertainment. Take a stroll around the lake or enjoy water sports right from your backyard.\nNeighborhood Description: Experience the tranquility of lakeside living in this picturesque neighborhood. Surrounded by peaceful water views, local parks, and plenty of outdoor activities, Lakeside Retreat is the ideal community for nature lovers. Don't miss out on the opportunity to own a piece of this serene lakeside paradise.", metadata={'source': './listings_1.csv', 'row': 6}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Historic District with total size of  3,500 sqft. Number of bedrooms and bathrooms in the house is  6 and  4 respectively. Price of the house is  $1,500,000\nDescription: Immerse yourself in the rich history of this charming 6 bedroom, 4 bathroom home in the Historic District. This beautifully restored Victorian boasts intricate details, a spacious backyard, and a separate guest house. Enjoy the convenience of living just steps away from quaint shops, restaurants, and local attractions.\nNeighborhood Description: Step back in time and stroll through the charming streets of the Historic District. With well-preserved historic homes, quaint shops, and local landmarks, this neighborhood is full of character and nostalgia. Come see why residents take great pride in calling this neighborhood home.', metadata={'source': './listings_1.csv', 'row': 7}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Golf Course Community with total size of  4,000 sqft. Number of bedrooms and bathrooms in the house is  5 and  4 respectively. Price of the house is  $900,000\nDescription: Live the resort lifestyle in this spacious and elegant 5 bedroom, 4 bathroom home in the prestigious Golf Course Community. This luxurious home offers a private pool and spa, a gourmet kitchen, and breathtaking golf course views. Join the country club and enjoy access to golf, tennis, and exclusive amenities.\nNeighborhood Description: Tee off in style and experience the luxurious lifestyle of this prestigious golf course community. With immaculately maintained courses, a stunning clubhouse and exclusive amenities, this neighborhood is perfect for those who enjoy the finer things in life. Treat yourself to resort-style living in Golf Course Community.', metadata={'source': './listings_1.csv', 'row': 8}),
 Document(page_content="Basic Description: This house exists in the neighborhood of  Arts District with total size of  1,800 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is  $800,000\nDescription: This modern and sleek 3 bedroom, 2 bathroom loft is located in the vibrant Arts District. With high ceilings, an open floor plan, and plenty of natural light, this home is perfect for artists and creatives. Explore the neighborhood's galleries, eateries, and entertainment options, all just steps away from your front door.\nNeighborhood Description: Immerse yourself in the creative and bustling atmosphere of the Arts District. This eclectic neighborhood is home to local galleries, studios, and unique dining options. Lose yourself in the vibrant energy of this neighborhood, where inspiration is just around the corner.", metadata={'source': './listings_1.csv', 'row': 9}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Country Living with total size of  2,000 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $450,000\nDescription: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.\nNeighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.', metadata={'source': './listings_1.csv', 'row': 10}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Riverfront with total size of  4,500 sqft. Number of bedrooms and bathrooms in the house is  6 and  4 respectively. Price of the house is  $1,800,000\nDescription: Treat yourself to luxury living in this elegant 6 bedroom, 4 bathroom riverfront estate. Boasting high-end finishes, a private boat dock, and breathtaking river views, this home offers the perfect blend of comfort and sophistication. Enjoy outdoor activities right from your backyard or relax in the serenity of your own private oasis.\nNeighborhood Description: Experience the ultimate waterfront lifestyle in this exclusive riverfront community. With stunning river views, private boat slips, and easy access to water activities, this neighborhood is perfect for boating enthusiasts and nature lovers alike. Come see why Riverfront is one of the most sought-after communities in the area.', metadata={'source': './listings_1.csv', 'row': 11}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Family-Friendly Subdivision with total size of  3,000 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $650,000\nDescription: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.\nNeighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.', metadata={'source': './listings_1.csv', 'row': 12}),
 Document(page_content="Basic Description: This house exists in the neighborhood of  Oceanview with total size of  2,500 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is  $2,200,000\nDescription: Wake up to breathtaking ocean views in this stunning 3 bedroom, 2 bathroom home in Oceanview. This modern and elegant residence offers high-end finishes, a gourmet kitchen, and a private balcony with panoramic views of the Pacific. Walk to nearby beaches or relax in your own personal oasis.\nNeighborhood Description: Indulge in the coastal lifestyle in the elite neighborhood of Oceanview. With picturesque ocean views, easy access to the beach, and a laid-back atmosphere, this community is perfect for those who love the ocean. Don't miss your chance to live in one of the most sought-after neighborhoods in the area.", metadata={'source': './listings_1.csv', 'row': 13}),
 Document(page_content='Basic Description: This house exists in the neighborhood of  Gated Community with total size of  5,000 sqft. Number of bedrooms and bathrooms in the house is  5 and  4 respectively. Price of the house is  $2,500,000\nDescription: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.\nNeighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.', metadata={'source': './listings_1.csv', 'row': 14})]

In [4]:
model_name = 'gpt-3.5-turbo'
llm = OpenAI(model_name=model_name, temperature=0, max_tokens=1000, openai_api_key="YOUR_API_KEY")

/opt/conda/lib/python3.10/site-packages/langchain/llms/openai.py:202: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/langchain/llms/openai.py:790: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(

In [6]:
embeddings = OpenAIEmbeddings(openai_api_key="YOUR_API_KEY")

In [8]:
db = Chroma.from_documents(docs, embeddings)
print(db._collection.count())

15

In [9]:
db

In [10]:
q1 =  "What is your total budget for house purchase?"
q2 = "How many bedrooms you need in the house?"
q3 = "How many bathrooms you need in the house?"
q4 = "What is the house size you are looking for?"
q5 = "Any other environmental, transportational or any other preference you have. To skip please enter NA"
q_list = [q1, q2, q3, q4 , q5]
q_list

['What is your total budget for house purchase?',
 'How many bedrooms you need in the house?',
 'How many bathrooms you need in the house?',
 'What is the house size you are looking for?',
 'Any other environmental, transportational or any other preference you have. To skip please enter NA']

In [46]:
def ask_questions_query(q_list):
    """
    This function takes input from user and creates and returns query utilizing user responses
    """
    budget = input(q_list[0])
    br = input(q_list[1])
    bt = input(q_list[2])
    hs = input(q_list[3])
    misc = input(q_list[4])
    query = f'A house with approx total size of  {hs} sqft. Number of bedrooms and bathrooms in the house is  {br} and  {bt} respectively. Price of the house is approx {budget}. Other requirements are {misc}'
    return query

In [47]:
def semantic_search(query):
    """
    This function takes query and return top 3 similar searches from vector database
    """
    similar_docs = db.similarity_search(query, k=2)
    return similar_docs

In [49]:
def gen_aug_listing(similar_docs, template, query):
    """
    This function takes matching document, template and query
    and created augmented listings
    """
    for ind, context in enumerate(similar_docs):
        temperature = 0.0
        model = "gpt-3.5-turbo-instruct"
        response = openai.Completion.create(
            model = model,
            prompt = template.format(query=query, context=context),
            max_tokens = 1000,
            temperature=temperature            
            )
        output = response['choices'][0]['text'].strip()
        print(f'\n\n ######### Listing {ind} ##########')
        print(output)

In [50]:
def run_app(template):
    """
    This function creates query based on user inputs
    Runs similarity Search
    Generates augmented listings
    using respective functions
    """
    query = ask_questions_query(q_list)
    print(f' ##\n Query: {query} \n ###')
    similar_docs = semantic_search(query)
    print(f'printing similar docs ##### {similar_docs} ######')
    print("########### AUGMENTED LISTINGS BASED ON USER INPUT ########")
    gen_aug_listing(similar_docs, template, query)

In [70]:
template = """
Personalize the following real estate listing description as given in Context.
Please do not alter the information on number of bedrooms, bathrooms, price and house size given in Context
Context: {context}


Buyer Preferences: {query}
"""

In [71]:
print(template)

Personalize the following real estate listing description as given in Context.
Please do not alter the information on number of bedrooms, bathrooms, price and house size given in Context
Context: {context}


Buyer Preferences: {query}

In [72]:
run_app(template)

What is your total budget for house purchase?500000
How many bedrooms you need in the house?4
How many bathrooms you need in the house?
What is the house size you are looking for?3000
Any other environmental, transportational or any other preference you have. To skip please enter NAaway from city
 ##
 Query: A house with approx total size of  3000 sqft. Number of bedrooms and bathrooms in the house is  4 and   respectively. Price of the house is approx 500000. Other requirements are away from city
 ###
printing similar docs ##### [Document(page_content='Basic Description: This house exists in the neighborhood of  Country Living with total size of  2,000 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $450,000\nDescription: Enjoy the peace and quiet of country living in this charming 4 bedroom, 3 bathroom farmhouse. This home boasts a spacious wrap-around porch, a bright and open kitchen, and a large backyard for outdoor entertaining. Take a deep breath and relax in this tranquil, rural setting.\nNeighborhood Description: Get away from the noise and chaos of the city and experience the simplicity of country living. With vast open spaces, fresh air, and a tight-knit community, this neighborhood offers a peaceful and laid-back lifestyle. Escape to the countryside in this idyllic Country Living community.', metadata={'row': 10, 'source': './listings_1.csv'}), Document(page_content='Basic Description: This house exists in the neighborhood of  Family-Friendly Subdivision with total size of  3,000 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $650,000\nDescription: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.\nNeighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.', metadata={'row': 12, 'source': './listings_1.csv'})] ######
########### AUGMENTED LISTINGS BASED ON USER INPUT ########


 ######### Listing 0 ##########
Looking for a peaceful retreat away from the hustle and bustle of the city? Look no further than this charming farmhouse located in the tranquil neighborhood of Country Living. With a total size of 2,000 sqft, this 4 bedroom, 3 bathroom home offers plenty of space for you and your family to spread out and relax. Step onto the spacious wrap-around porch and take in the fresh country air, or gather with friends and family in the large backyard for outdoor entertaining. With a bright and open kitchen, this home is perfect for hosting gatherings and creating lasting memories. And with a price of $450,000, this idyllic country home is within your budget. Don't miss out on the opportunity to escape to the countryside and experience the simplicity of country living.


 ######### Listing 1 ##########
Welcome to your dream home in the highly sought-after Family-Friendly Subdivision! This spacious 4 bedroom, 3 bathroom house boasts a total size of 3,000 sqft, providing ample space for your growing family. With a price of $650,000, this home offers exceptional value for its size and location.

Enjoy making memories with your loved ones in the open concept layout, perfect for entertaining and spending quality time together. The large backyard is ideal for outdoor activities and gatherings, and the community amenities such as the pool and playground add to the family-friendly atmosphere.

Located in a quiet and peaceful neighborhood, this home is away from the hustle and bustle of the city, providing a serene and safe environment for your family. Top-rated schools and entertainment options are just a short distance away, making this location ideal for families.

Experience the warmth and friendliness of the Family-Friendly Subdivision, where community spirit is strong and family-friendly activities are abundant. This neighborhood offers the perfect setting to raise a family, with all the necessary amenities and a welcoming atmosphere. Don't miss out on the opportunity to call this place home. Schedule a viewing today!

In [73]:
run_app(template)

What is your total budget for house purchase?400000
How many bedrooms you need in the house?3
How many bathrooms you need in the house?2
What is the house size you are looking for?2500
Any other environmental, transportational or any other preference you have. To skip please enter NAnear shopping mall
 ##
 Query: A house with approx total size of  2500 sqft. Number of bedrooms and bathrooms in the house is  3 and  2 respectively. Price of the house is approx 400000. Other requirements are near shopping mall
 ###
printing similar docs ##### [Document(page_content='Basic Description: This house exists in the neighborhood of  Gated Community with total size of  5,000 sqft. Number of bedrooms and bathrooms in the house is  5 and  4 respectively. Price of the house is  $2,500,000\nDescription: Live in luxury and privacy in this exquisite 5 bedroom, 4 bathroom home in a coveted gated community. This home offers top-of-the-line finishes, a private pool and spa, and scenic mountain views. Enjoy the safety and exclusivity of a gated community, while still being just a short drive away from city amenities.\nNeighborhood Description: Experience the ultimate in exclusivity and security in the prestigious Gated Community. With lush landscaping, grand entrance gates, and top-notch security, this neighborhood offers the utmost privacy and tranquility. Live surrounded by luxury and serenity in this highly sought-after neighborhood.', metadata={'row': 14, 'source': './listings_1.csv'}), Document(page_content='Basic Description: This house exists in the neighborhood of  Family-Friendly Subdivision with total size of  3,000 sqft. Number of bedrooms and bathrooms in the house is  4 and  3 respectively. Price of the house is  $650,000\nDescription: Make memories with your family in this spacious 4 bedroom, 3 bathroom home in the desirable Family-Friendly Subdivision. With an open concept layout, a large backyard, and access to community amenities like a pool and playground, this home is perfect for families. Conveniently located near top-rated schools and entertainment options.\nNeighborhood Description: Discover the perfect place to raise a family in the warm and friendly Family-Friendly Subdivision. With a strong sense of community, a variety of family-friendly activities and top-rated schools, this neighborhood offers everything a growing family needs. Experience the joy of family life in this welcoming community.', metadata={'row': 12, 'source': './listings_1.csv'})] ######
########### AUGMENTED LISTINGS BASED ON USER INPUT ########


 ######### Listing 0 ##########
Looking for a luxurious and private home in a highly sought-after neighborhood? Look no further than this stunning 5 bedroom, 4 bathroom house located in the prestigious Gated Community. With a total size of 5,000 sqft, this home offers ample space for comfortable living. The top-of-the-line finishes, private pool and spa, and scenic mountain views make this home a true gem.

Experience the ultimate in exclusivity and security in this coveted gated community. With lush landscaping, grand entrance gates, and top-notch security, you can enjoy the utmost privacy and tranquility. This neighborhood is perfect for those who value safety and exclusivity, while still being just a short drive away from city amenities.

This home is perfect for those who prefer a smaller living space, with a total size of approximately 2,500 sqft. It offers 3 bedrooms and 2 bathrooms, making it ideal for a small family or those looking for a cozy yet luxurious home. The price of this home is approximately $400,000, making it a great value for the amenities and location it offers.

Conveniently located near a shopping mall, this home offers the best of both worlds - privacy and convenience. Don't miss out on the opportunity to live in this highly desirable neighborhood. Schedule a viewing today and experience the luxury and serenity of this gated community for yourself.


 ######### Listing 1 ##########
Welcome to your dream home in the highly sought-after Family-Friendly Subdivision! This spacious 4 bedroom, 3 bathroom house boasts a total size of 3,000 sqft, providing plenty of room for your growing family. With an open concept layout, you can easily entertain guests while preparing meals in the modern kitchen. Step outside to your large backyard, perfect for hosting summer barbecues or letting the kids run around.

As a resident of this family-friendly neighborhood, you'll have access to community amenities such as a pool and playground, making it easy to stay active and socialize with your neighbors. Plus, with top-rated schools and entertainment options just a short distance away, you'll have everything you need right at your fingertips.

This home is priced at $650,000, offering great value for the size and location. And for those who prefer a slightly smaller home, this house also meets your requirements with a total size of 2,500 sqft, 3 bedrooms, and 2 bathrooms. You'll also love the convenience of living near a shopping mall, making errands and shopping a breeze.

Don't miss out on the opportunity to make memories with your family in this welcoming community. Come see this home today and experience the warmth and sense of community that Family-Friendly Subdivision has to offer.